### ISSUE TITLE
Snippet state is not considered while publishing pages

### ISSUE THREAD

**Issue by chirimoya** [sulu-io/sulu#1099]
Also add `state` as list column.

**Comment by berndhep** [comment]
Remove publishing status feature from Snippets (only in the frontend) & set standard value to published.

**Comment by wachterjohannes** [comment]
ui changes done in this PR if this should be undo sometime https://github.com/sulu-io/sulu/commit/600d9ccc138f29ce6b565ae41d1159778dc74e5a
