### ISSUE TITLE
Changing the resource locator of a page to a previously used one leads to a server error

### ISSUE THREAD

**Issue by sabinebaer** [sulu-io/sulu#1112]
A server error occurs when changing the resource locator to one that was already used for this page and is therefore included in the history. Should display a meaningful message instead.

Exception:
```
request.CRITICAL: Uncaught PHP Exception Sulu\Component\Content\Exception\ResourceLocatorAlreadyExistsException: "" at /myproject/vendor/sulu/sulu/src/Sulu/Component/Content/Types/Rlp/Mapper/PhpcrMapper.php line 571 {"exception":"[object] (Sulu\\Component\\Content\\Exception\\ResourceLocatorAlreadyExistsException(code: 0):  at /myproject/vendor/sulu/sulu/src/Sulu/Component/Content/Types/Rlp/Mapper/PhpcrMapper.php:571)"}
```

**Comment by wachterjohannes** [comment]
@sabinebaer i think the exception is right. perhaps we could notice that its a history url and restore it, but i think giving a clear message would help here!

**Comment by danrot** [comment]
@wachterjohannes The problem is that the response has a 500 error code, whereby it should be some 400 (maybe 409 for conflict?) code.

**Comment by wachterjohannes** [comment]
@danrot yeah that right (= it should be handled but it is correct that there is an exception!

**Comment by danrot** [comment]
@wachterjohannes But then it is not a server error anymore. And btw, there should be displayed a better error label, nobody knows what is going on when this happens. That's what this issue really is about :wink:

**Comment by wachterjohannes** [comment]
@danrot thats what i thought before (=
