### ISSUE TITLE
Use a smaller version of the Sulu logo for the Symfony toolbar

### ISSUE THREAD

**Issue by sabinebaer** [sulu-io/sulu#1114]
The Sulu logo used for the Symfony toolbar has a size of 500x500px. When setting "height: auto" on the img tag on a website the Sulu logo is shown in its original size and therefore the Symfony toolbar is shown with a height of 500px.

![sulu-logo-symfony-toolbar](https://cloud.githubusercontent.com/assets/5627878/7743971/d0e71692-ff9f-11e4-9fb7-0b328ba9cd51.png)

**Comment by dantleech** [comment]
omg

**Comment by wachterjohannes** [comment]
i had take at this and its easy (= haha the other logos are resized to the size 24x24px so they are not interested in max-width! i think we should do this too! Also in the HTML of the profiler icon are some strange tag which i think belongs to TWIG perhaps there is a syntax issue!

**Comment by wachterjohannes** [comment]
@sabinebaer sorry i have forgotten it after the hackdays (=

**Comment by danrot** [comment]
Probably it would be even better and more performant if the logo already has the correct size :P
