### ISSUE TITLE
Search term is cut off in the Sulu search in Firefox

### ISSUE THREAD

**Issue by sabinebaer** [sulu-io/sulu#1117]
Tested with 38.0.1 for Mac OS:

![sulu-search-firefox](https://cloud.githubusercontent.com/assets/5627878/7745715/90e7b78c-ffad-11e4-9ece-9db8ebcd5848.png)

**Comment by 3rfan** [comment]
@sabinebaer maybe it's a fixed issue because it is looking fine in the current version of chrome :/

**Comment by alexander-schranz** [comment]
@3rfan chrome looks good but firefox not

**Comment by 3rfan** [comment]
@alexander-schranz ok. reading the complete title also helps a lot ;)
