### ISSUE TITLE
Language chooser should be available in media edit

### ISSUE THREAD

**Issue by c00n84** [sulu-io/sulu#1121]
![bildschirmfoto 2015-05-22 um 09 03 03](https://cloud.githubusercontent.com/assets/841720/7765703/6631d752-0061-11e5-958c-d30bf475b48b.png)

**Comment by wachterjohannes** [comment]
related https://github.com/sulu-io/sulu/issues/960

**Comment by danrot** [comment]
not only related, actually it is a duplicate of #960, so it should be closed.
