### ISSUE TITLE
Changelanguage on new page ends in 404

### ISSUE THREAD

**Issue by alexander-schranz** [sulu-io/sulu#1142]
When I add a new Page to my webspace without saving switch to another language it will end in 404. It requests then the ID undefined (http://sulu.lo/admin/#content/contents/sulu_io/en/edit:undefined/content).

**Comment by wachterjohannes** [comment]
@alexander-schranz i think this is related to this PR which is already merged and it should be released with the next version https://github.com/sulu-io/sulu/pull/996

**Comment by alexander-schranz** [comment]
thats awesome thx.
duplicated with #823
