### ISSUE TITLE
Downloadlink not available in media overlay

### ISSUE THREAD

**Issue by alexander-schranz** [sulu-io/sulu#1150]
- [x] Media Overlay should have a download link #1275
 - [ ] The Download Button should be an `A` Tag with `href` for simple right click and copy link

**Comment by danrot** [comment]
@alexander-schranz You are talking about the collection view here, not about the media assignment, right?

**Comment by danrot** [comment]
@alexander-schranz Add cloud icon to the version in the history list.

**Comment by alexander-schranz** [comment]
@danrot yes about the collection view
