### ISSUE TITLE
FatalError when no hostname does not correspond to webspace hosts.

### ISSUE THREAD

**Issue by dantleech** [sulu-io/sulu#1198]
````
FatalErrorException in ExceptionController.php line 66:
Error: Call to a member function getTheme() on null
````

To reproduce:

- Change the hostnames in `sulu.lo.xml` to something else.
- Visit the homepage.

**Comment by memoryleak** [comment]
Having this issue on master with commit 903e57774334ad60907d51d7b90cc4328bce403e

**Comment by danrot** [comment]
@memoryleak The actual issue you have is probably https://github.com/sulu-io/sulu/issues/233

Until we have changed that, the file has to be called example_com.xml, so that the filename matches the key in the xml.

**Comment by npotier** [comment]
Hi,

I'm still having this issue. 
![image](https://cloud.githubusercontent.com/assets/1151094/9773716/3165965a-5744-11e5-8376-8313807d445d.png)

Has anything changed this your last message ?

**Comment by danrot** [comment]
I am really sry about this error, it's not really a good one... The problem is that your webspace configuration file has an error, can you maybe post it here?

**Comment by chirimoya** [comment]
https://github.com/sulu-io/sulu-standard/pull/601

**Comment by wachterjohannes** [comment]
if you have no (valid) webspaces for the current url you get now a "good" exception (https://github.com/sulu-io/sulu/pull/2131/files#diff-57062b7cba5a675fe02d37fa805cc4deR68) this helps you to find the mistake earlier.

**Comment by danrot** [comment]
Sounds to me like we can close this issue :smiley:
