### ISSUE TITLE
Smart content choice is empty after selecting

### ISSUE THREAD

**Issue by dantleech** [sulu-io/sulu#1209]
After selecting a smart content source and saving, the smart content list is empty, and it remains empty upon page refresh.

Reproduce:

- Create a page
- Switch to the `overview` template`
- Add some smart content
- Save
- Go back to the smart content dialog, `Quelle Wahlen`, and the list is empty

**Comment by chirimoya** [comment]
@wachterjohannes can you verify? close issue, if you can't reproduce.

**Comment by wachterjohannes** [comment]
@chirimoya i cannot reproduce this.
