### ISSUE TITLE
Use version 1.2.* of liip/theme-bundle to support multiple themes/assetic_integration

### ISSUE THREAD

**Issue by sabinebaer** [sulu-io/sulu#1217]

**Comment by danrot** [comment]
Haven't you already changed that in a project? Then it shouldn't be too much work to create a PR :smile:

**Comment by sabinebaer** [comment]
Yes, I included it but the only thing I can verify at the moment is that assetic:dump stopped throwing errors for multiple themes in multiple bundles. I can not test anything else as there are too many other issues in this project (because of the upgrade and the usage of the portal key).

**Comment by danrot** [comment]
Ok, then please create a PR as soon as you verify.

**Comment by danrot** [comment]
Already created https://github.com/sulu-io/sulu/pull/1244 and updated to 1.3.*
