### ISSUE TITLE
Missing select box in copy language overlay

### ISSUE THREAD

**Issue by c00n84** [sulu-io/sulu#1225]
![bildschirmfoto 2015-06-11 um 15 38 27](https://cloud.githubusercontent.com/assets/841720/8108326/0f376dc8-1050-11e5-808b-680229c21c61.png)

**Comment by wachterjohannes** [comment]
@c00n84 could you give a bit more informations? has this page concrete languages? or is this the only language? javascript errors?

**Comment by c00n84** [comment]
@wachterjohannes The page is in DE. I change to EN in the navigation column view. Afterwards I want to do a language copy from DE to EN by click on the edit icon. Then the overlay appears.

I've analysed it:
- no javascript errors
- no errors in the admin backend log file
- no abnormality in the PHPCR shell

I tried it with other pages of the portal and it worked.

**Comment by wachterjohannes** [comment]
@c00n84 thats really strange ... we should analyze this on monday, perhaps there is something special on this page ... a collision or something similar ...

**Comment by wachterjohannes** [comment]
maybe related #1010
