### ISSUE TITLE
Enable doctrine metadata cache for production

### ISSUE THREAD

**Issue by chirimoya** [sulu-io/sulu#1229]
http://symfony.com/doc/current/reference/configuration/doctrine.html

**Comment by danrot** [comment]
I don't know if this is o easy to address. You already have to configure what kind of cache (apc, memcache, ...) you want to use and depending on the cache also some ports and other stuff. I don't think that we want to force the use of one of these caches in sulu-standard...

**Comment by wachterjohannes** [comment]
we could make it configurable with some defaults in dist files?

**Comment by danrot** [comment]
Then it would IMO be more important to split the configuration, so that the user can configure whatever he wants.

@chirimoya APC is also a separate extension which has to be installed, so it is also not a good default value IMO.

**Comment by chirimoya** [comment]
`file_system` ?

**Comment by danrot** [comment]
`file_system` would work, but is currently not supported by the DoctrineBundle. Another solution would be to create a separate service, but if the user uses a different caching mechanism we have a useless service polluting the container.

My suggestion would be to write a cookbook article in the docs. Once this is done this issue can be closed.

**Comment by chirimoya** [comment]
+1 cookbook article
