### ISSUE TITLE
Make command for cleaning url history before online going

### ISSUE THREAD

**Issue by c00n84** [sulu-io/sulu#1239]
I want to clean my url history before a website is going live. Often the clients move pages, change titles and the urls and so there are many entries in the url history which aren't needed.

**Comment by dantleech** [comment]
I think you should be able to do this in the shell at least:

````
PHPCRSH> DELETE FROM [nt:unstructured] WHERE [jcr:mixinTypes] = 'sulu:path' AND [sulu:history] = 1
PHPCRSH> save
`````

or similar /cc @wachterjohannes

**Comment by wachterjohannes** [comment]
@dantleech i will create a command with a parameter for locale and webspace! and optional a part of the url to delete it from a part of the tree!
