### ISSUE TITLE
Add header for Wappalyzer "X-Powered-By: Sulu"

### ISSUE THREAD

**Issue by joemoe** [sulu-io/sulu#1247]
Maybe we should think about, whether it is a security risk.

**Comment by danrot** [comment]
Well, if you rely on security by obscurity anything that tells the system behind it can be considered a security vulnerability. But that's what we basically need for Wappalyzer, right?

**Comment by joemoe** [comment]
of course you're right!

**Comment by joemoe** [comment]
so do it. :)

**Comment by danrot** [comment]
That would be a great topic for somebody to solve on the hackday this saturday :-)
