### ISSUE TITLE
Better exception message when template key in XML file does not match filename

### ISSUE THREAD

**Issue by dantleech** [sulu-io/sulu#1266]
Currently

````
a valid template with key "layout_info" and file "/<PATH>/app/Resources/snippets/layout_info.xml" cannot be found 
````

Should read:

````
the template in file "/<PATH>/app/Resources/snippets/layout_info.xml" is defined as "%s" instead of "layou_info"
````

Or similar.

**Comment by danrot** [comment]
IMO this is somehow related to #233, so that this error can't occur at all anymore. But I would say that the filename should be used instead of the key, so that the key can be safely removed. Can we add this information to the other issue, and close this one?

**Comment by dantleech** [comment]
Makes sense as long as we are defining only one template per file.
