### ISSUE TITLE
Smart Content - change source - not working anymore

### ISSUE THREAD

**Issue by thomasduenser** [sulu-io/sulu#1274]
![bildschirmfoto 2015-06-22 um 10 44 21](https://cloud.githubusercontent.com/assets/3875917/8278459/b9fc414c-18cb-11e5-85db-c6ae895bd1d7.png)

When trying to change the data source of a smart content in the backend, the list is empty and can't be changed. Seems like it doesn't even send a network request.

I think this bug exists since RC1 or RC2.

**Comment by wachterjohannes** [comment]
@thomasduenser which node do you have selected? could it be that its the "root" node of a webspace?

**Comment by wachterjohannes** [comment]
@thomasduenser ok now i can reproduce it with all pages!
