### ISSUE TITLE
using own user implementation

### ISSUE THREAD

**Issue by christoph-hautzinger** [sulu-io/sulu#1301]
Hello dudes,

I created my own user implementation and extended it from sulu base user class:

```php
<?php

namespace Hautzi\Bundle\WebsiteBundle\Entity;

use Doctrine\ORM\Mapping AS ORM;
use Sulu\Bundle\SecurityBundle\Entity\User as BaseUser;

/**
 * @ORM\Entity
 */
class User extends BaseUser
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @ORM\OneToMany(targetEntity="Hautzi\Bundle\WebsiteBundle\Entity\TimelineItem", mappedBy="responsiblePerson")
     */
    private $timelineResponsibilites;

    /**
     * @ORM\OneToMany(targetEntity="Hautzi\Bundle\WebsiteBundle\Entity\TimelineItem", mappedBy="creator")
     */
    private $timelineItems;

    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }
}

```

then I changed doctrine/orm/resolve_target_entities in `app/config/config.yml` to use this implementation

```php
        resolve_target_entities:
            Sulu\Component\Security\UserInterface: Hautzi\Bundle\WebsiteBundle\Entity\User
```

For relations everything works fine, but unfortunately when fetching a user from the Symfony security `TokenStorage`, I will receive the "wrong" Sulu User instance `Sulu\Bundle\SecurityBundle\Entity\User`.

Is there a way to configure an own user implementation that it is used across the whole application?

**Comment by chirimoya** [comment]
We are currently improving the persistence handling. This PR will be merged soon and will fix this issue. https://github.com/sulu-io/sulu/pull/1300
