### ISSUE TITLE
500 error when content template has no RLP tag

### ISSUE THREAD

**Issue by dantleech** [sulu-io/sulu#131]
If the `sulu.rlp` tag is required then there should be some kind of validation - or the URL should be automatically generated if this tag is absent based on the node-name.

**Comment by dantleech** [comment]
Can we solve this by making the URL/RespourceLocator mandatory? (why is this in the "ready" column?)

**Comment by danrot** [comment]
Because we already said that this is solved by a better template validation. Means for me that the resource locator is mandatory for the pages, but not for the snippets.

**Comment by berndhep** [comment]
@wachterjohannes Please make this fertig.
