### ISSUE TITLE
Image conversion fails when open_basedir is enabled

### ISSUE THREAD

**Issue by kriswillis** [sulu-io/sulu#1312]
On a host whose PHP `open_basedir` directive is set (even to include `/tmp`), once an image has been uploaded in the Assets administration, the following uncaught exception is logged, and image thumbnails are not generated.

    request.INFO: Matched route "sulu_media.website.image.proxy" (parameters: "_controller": "Sulu\Bundle\MediaBundle\Controller\MediaStreamController::getImageAction", "slug": "200x200/02/22-0010.jpg", "_route": "sulu_media.website.image.proxy") [] []
    request.CRITICAL: Uncaught PHP Exception Imagine\Exception\InvalidArgumentException: "File  does not exist." at /var/www/foo/vendor/imagine/imagine/lib/Imagine/Image/AbstractImagine.php line 67 {"exception":"[object] (Imagine\\Exception\\InvalidArgumentException(code: 0): File  does not exist. at /var/www/foo/vendor/imagine/imagine/lib/Imagine/Image/AbstractImagine.php:67)"} []

**Comment by alexander-schranz** [comment]
Hi,

thank you for your report.
maybe I got my error can you please try when you change in the following file:
`vendor/sulu/sulu/src/Sulu/Bundle/MediaBundle/Media/FormatManager/FormatManager.php`

the following line
http://github.com/sulu-io/sulu/blob/1.0.0-RC3/src/Sulu/Bundle/MediaBundle/Media/FormatManager/FormatManager.php#L444

into:

``` php
$tempFile =  tempnam(sys_get_temp_dir(), 'media_original');
```

if this don't work can you maybe post a trace?

**Comment by kriswillis** [comment]
Yes, I figured this out before reporting, working on a PR at the moment!

**Comment by alexander-schranz** [comment]
:+1 thank you!

**Comment by danrot** [comment]
@alexander-schranz Will this line always use the temp directory of the system? Is that really what we want? Aren't we currently having issues with that?

**Comment by alexander-schranz** [comment]
@danrot this should work fine, because tempnam(null) would do the same but is not working with the open_basedir. I only remember the old issue was that the path(/tmp) was hardcoded.

**Comment by danrot** [comment]
I guess I am just too far away from this :-) Are the generated images moved away from the `/tmp` directory later?

**Comment by kriswillis** [comment]
@danrot The temp files are removed shortly after: 

https://github.com/sulu-io/sulu/blob/develop/src/Sulu/Bundle/MediaBundle/Media/FormatManager/FormatManager.php#L206

**Comment by alexander-schranz** [comment]
yes after the image is generated they are moved into the public folder `my_project_path/web/uploads/media/...`  
so all following requests will not call the controller again.
