### ISSUE TITLE
Search in overlay for adding snippets

### ISSUE THREAD

**Issue by crash0verride** [sulu-io/sulu#1328]
As a user with several 1000 snippets, I want to search for a snippet in the overlay for adding snippets to a page. A fuzzy search would be nice.

**Comment by danrot** [comment]
@berndhep Do we already have a design for that?

**Comment by berndhep** [comment]
@danrot 
![bildschirmfoto 2015-11-05 um 11 24 56](https://cloud.githubusercontent.com/assets/7425459/10965841/dce9dc06-83af-11e5-8977-b774bbcde3b7.png)
