### ISSUE TITLE
Functionality to copy a snippet into another language

### ISSUE THREAD

**Issue by thomasduenser** [sulu-io/sulu#1331]
A functionality to copy a snippet from one locale to another would be great - we already have the possibility with following command `sulu:snippet:locale-copy` but not in the SULU backend.

**Comment by wachterjohannes** [comment]
TODO List:

- [ ] shadow language in list (like column view)
- [ ] overlay when open a "ghost"
- [ ] overlay in form
- [ ] language changer in list

**Comment by wachterjohannes** [comment]
we will add the language changer with the new header
