### ISSUE TITLE
Contact Birthday not shown when before 1900

### ISSUE THREAD

**Issue by alexander-schranz** [sulu-io/sulu#1333]
The contacts come from an import when the birthday of the contact is before 1900 (e.g. 1889-01-01) the birthday is not shown in the sulu backend.

**Comment by danrot** [comment]
That's probably an issue with the datepicker...

**Comment by alexander-schranz** [comment]
yes the config of the datepicker is set a `from` 1900

**Comment by danrot** [comment]
If this is just a config it sounds like an easy pick ;-)

**Comment by alexander-schranz** [comment]
should be an easy fix. I would allow every date, because we don't know which historical or futurostic `contacts` our users want to store.
