### ISSUE TITLE
File Download not working with special characters

### ISSUE THREAD

**Issue by thomasduenser** [sulu-io/sulu#1337]
When uploading an image with special characters like the german Umlaute, the download isn't working. Example filename: `wöchentlicher_plan.pdf`

![bildschirmfoto 2015-07-03 um 10 10 38](https://cloud.githubusercontent.com/assets/3875917/8495190/ca05128c-216b-11e5-8758-2b09fe01ff63.png)

**Comment by alexander-schranz** [comment]
seems like the problem is the disposition header
```
$disposition = $response->headers->makeDisposition(
            $dispositionType,
            basename($fileName)
);
```

here we need to add the third parameter which only contains ascii only characters
