### ISSUE TITLE
Missing translate on sulu password forget function

### ISSUE THREAD

**Issue by alexander-schranz** [sulu-io/sulu#1340]
![bildschirmfoto 2015-07-06 um 16 25 01](https://cloud.githubusercontent.com/assets/1698337/8524441/9deafbe8-23fb-11e5-837b-4e252d6c673a.png)

**Comment by wachterjohannes** [comment]
@alexander-schranz hmm which version of sulu is that?

![image](https://cloud.githubusercontent.com/assets/1464615/8776061/7fee56a0-2eee-11e5-8de3-6c95559d008a.png)

**Comment by alexander-schranz** [comment]
was 1.0 but on current version 1.0.2 it looks good
