### ISSUE TITLE
Contact Documents are not sortable

### ISSUE THREAD

**Issue by thomasduenser** [sulu-io/sulu#1374]
ContactBundle -> it's not possible to sort the documents / images in the "Documents" Tab. If the sort order is changed and the save button clicked, it never stops to pulsate.

![bildschirmfoto 2015-07-14 um 17 03 48](https://cloud.githubusercontent.com/assets/3875917/8676517/55fe2d32-2a4a-11e5-9e85-4920024b7c28.png)

**Comment by danrot** [comment]
I don't know why it doesn't stop loading, but sorting is currently not supported here, because we don't have a `order` property in the database...

**Comment by berndhep** [comment]
This list will be refactored and should not be sortable.
