### ISSUE TITLE
Duplicated collections in collection navigation

### ISSUE THREAD

**Issue by alexander-schranz** [sulu-io/sulu#1379]
I have the same collection with the same ID twice in the navigation. 
On the first and second site.

First request is:
http://sulu.lo/admin/api/collections?sortBy=title&page=1&limit=20
Here at the 19 place I have my collection with ID 2

http://sulu.lo/admin/api/collections?sortBy=title&page=2&limit=20
Here the first item is the same as the 19 and has the id 2 but the second is not the same as the 20.

The collection have meta in 3 locales `de, en, de_at`

**Comment by wachterjohannes** [comment]
@alexander-schranz can you maybe validate this issue because i cannot reproduce it in the current dev-develop version?

**Comment by alexander-schranz** [comment]
can also not reproduce on current version so will close this issue.
