### ISSUE TITLE
Snippet Datagrid should select checkbox on click

### ISSUE THREAD

**Issue by alexander-schranz** [sulu-io/sulu#1382]
add 

``` js
rowClickSelect: true,
```

to  initListToolbarAndList -> table -> viewOptions

**Comment by wachterjohannes** [comment]
the behaviour of the datagrid was fixed by @marcelmoosbrugger. so i think we can close this issue? @berndhep @danrot ?

**Comment by berndhep** [comment]
@wachterjohannes Jep, close
