### ISSUE TITLE
Snippets with Internal links inside blocks

### ISSUE THREAD

**Issue by leph24** [sulu-io/sulu#1383]
as soon as I use internal links inside block in snippets, I get an exception

**Comment by alexander-schranz** [comment]
can you add more information about the thrown exception? (message, trace)

**Comment by berndhep** [comment]
@leph24 please coordinate with @chirimoya

**Comment by leph24** [comment]
@chirimoya: I have used internal links inside blocks, which are used in snippets. The page shows an exception, when I have this combination, even if I don't use Snippets on a Template. Do you need the exact exception or are you going to try it by yourself?

**Comment by chirimoya** [comment]
@leph24 please add the exception with stacktrace.

**Comment by leph24** [comment]
@chirimoya: guess this issue isn't an issure in 1.0.3 anymore, it works fine now.
