### ISSUE TITLE
sulu_snippet_load with invalid uuid

### ISSUE THREAD

**Issue by leph24** [sulu-io/sulu#1384]
If the uuid is invalid, the sulu_snippet_load should return null instead of an exception

**Comment by wachterjohannes** [comment]
hmm i´m not shure that we should throw an exception here ... /cc @danrot what do you think?

**Comment by danrot** [comment]
If I understand @leph24 correctly there is currently an exception, and he would like the method to return null. And I think returning null is the better solution, because the user is able to delete the snippet, and if we throw an exception, the website won't work anymore.

**Comment by wachterjohannes** [comment]
ah yeah i haven´t read it carefully enough (: i would also return null
