### ISSUE TITLE
Rename "Text blocks" in "Content blocks"

### ISSUE THREAD

**Issue by berndhep** [sulu-io/sulu#1389]

**Comment by danrot** [comment]
@berndhep Where should that be changed? If it should be changed at the place the next screenshot is showing, it is already configureable anyway:

![image](https://cloud.githubusercontent.com/assets/405874/10220317/ba1b7df8-6846-11e5-9e16-72b1a7261e76.png)

**Comment by danrot** [comment]
Change the "Alle Textblöcke aufklappen" to "All Blöcke aufklappen", didn't find any other appearance.
