### ISSUE TITLE
Cache size could be very big and is slowing down the system

### ISSUE THREAD

**Issue by c00n84** [sulu-io/sulu#1390]
Cache size in /app/cache/admin/prod/sulu/preview is very big. For example I measured sizes of more than 500MB.

**Comment by danrot** [comment]
A first step to solve this would be to delete all generated cache files when the preview stops, but I am quite sure there will be some cases where orphaned data would be still around. However, it should probably be already a lot better like this.

**Comment by danrot** [comment]
@c00n84 Many files get deleted now, so this problem should not come up too fast again. It's still not possible to delete all the files, and the folders also remain... Please keep an eye on that, and reopen in case you are running into these kind of troubles again.
