### ISSUE TITLE
Filtering group_concat field descriptors does not work

### ISSUE THREAD

**Issue by turbo-ele** [sulu-io/sulu#1412]
the resulting sql is not correct and therefore not working ;)
i'm going to provide more information tomorrow

**Comment by chirimoya** [comment]
Tomorrow has passed ;-)

**Comment by turbo-ele** [comment]
the listbuilder is creating a query where it tries to apply a condition to the group_concated value.
actually it should then apply the condition to the original entity. 
e.g..: tags
```{sql}
... 
WHERE GROUP_CONCAT(tags.name) LIKE :tagname
```

should just be  

```{sql}
... 
WHERE tags.name LIKE :tagname
```

i guess

**Comment by chirimoya** [comment]
@wachterjohannes fixed?

**Comment by wachterjohannes** [comment]
is fixed by introducing a `getWhere` in the `FieldDescriptor`
