### ISSUE TITLE
Error after deleting filter while this filter is activated.

### ISSUE THREAD

**Issue by rs2487** [sulu-io/sulu#1426]
Result: its no longer possible so watch the list, or deaktivate the filter.
Workaround: choose another filter

**Comment by webmozart** [comment]
Why was this closed? IMO we should *always* document why an issue is closed to make it easier to remember that reason later on.

**Comment by wachterjohannes** [comment]
this was fixed a long time ago (: the datagrid now throws an event on error which reloads the datagrid without filters again.
