### ISSUE TITLE
Improve the API of the expressions used in the listbuilder

### ISSUE THREAD

**Issue by michaelzangerle** [sulu-io/sulu#1434]
The  idea was to remove the `QueryBuilder` from `getStatement` method of `AbstractDoctrineExpression` and move the method into the `EpxressionInterface`. The `QueryBuilder`could be passed as param in the constructor of each expression.

The problems lies within the `DoctrineListBuilder`. During the lifetime of an DoctrineListbuilder-Object three instances of the `QueryBuilder` will be created and two of them used to get the statements from the expressions. Furthermore none of these objects exist when the expressions are created.

**Comment by chirimoya** [comment]
@danrot ping
