### ISSUE TITLE
Image DisplayOptions Apperance

### ISSUE THREAD

**Issue by Quehnie** [sulu-io/sulu#1435]
If i only want to give the User a Left and Right displayOption, it looks like this:

![bildschirmfoto 2015-07-31 um 10 32 23](https://cloud.githubusercontent.com/assets/8446502/9003622/c1ca3510-376f-11e5-97d6-c8c3f5116183.png)

wouldn't it be better to look like this?

![bildschirmfoto 2015-07-31 um 10 33 01](https://cloud.githubusercontent.com/assets/8446502/9003636/d27f9a8a-376f-11e5-87b4-864d94dc6b59.png)

Because on Image One it more look like a page switch than a displayOption switch.

**Comment by wachterjohannes** [comment]
@berndhep what do you think?

**Comment by berndhep** [comment]
The second variation is the correct one. The new content type will have a different select (dropdown).

**Comment by danrot** [comment]
Seems to be fixed in the new design:
![image](https://cloud.githubusercontent.com/assets/405874/10422534/0dab0a10-70bc-11e5-8a6b-dac40cbba33b.png)
