### ISSUE TITLE
Block minOccurs 0 not working

### ISSUE THREAD

**Issue by alexander-schranz** [sulu-io/sulu#1454]
minOccurs 0 not working when set on  -1 it works.

**Comment by wachterjohannes** [comment]
additionally fix the xsd file for minOccurs and maxOccurs datatype

```xml
        <xs:attribute type="xs:byte" name="minOccurs" use="optional"/>
        <xs:attribute type="xs:byte" name="maxOccurs" use="optional"/>
```

* https://github.com/sulu-io/sulu/blob/771c4b74295c5be9e364b51b54e0a0b0abc97a8c/src/Sulu/Component/Content/Metadata/Loader/schema/template-1.0.xsd#L85
* https://github.com/sulu-io/sulu/blob/771c4b74295c5be9e364b51b54e0a0b0abc97a8c/src/Sulu/Component/Content/Metadata/Loader/schema/template-1.0.xsd#L102
