### ISSUE TITLE
CSS Grid not working in smartcontent overlay on windows

### ISSUE THREAD

**Issue by alexander-schranz** [sulu-io/sulu#1455]
The smartcontent overlay is looking terrible on windows when the scrollbar is activated.

![smartcontentoverlaygrid](https://cloud.githubusercontent.com/assets/1698337/9096903/79e65738-3bc0-11e5-9770-3c066c3889de.png)

**Comment by danrot** [comment]
Since the scrolling of overlays changed in the redesign, this is not an issue anymore.
