### ISSUE TITLE
Texteditor add Link Overlay missing OK Button

### ISSUE THREAD

**Issue by alexander-schranz** [sulu-io/sulu#1457]
Miss the OK Button on Link add in Texteditor

![addlinkoverlay](https://cloud.githubusercontent.com/assets/1698337/9097319/2c1d7c68-3bc3-11e5-81b6-8541fef49b3a.png)

Chrome on Windows

**Comment by wachterjohannes** [comment]
This should be fixed with version 1.0.5 ... if not please reopen
