### ISSUE TITLE
Contacts' documents tab does not save after dropping files for upload

### ISSUE THREAD

**Issue by kriswillis** [sulu-io/sulu#1463]
Steps to reproduce:

1. Edit a person within Contacts
2. Navigate to Documents tab
3. Click + icon on media select
4. Select a collection
5. Drag and drop a file for upload
6. Close media selection (without selecting newly uploaded file)
7. Click save icon in tool bar, icon animates indefinitely

**Comment by danrot** [comment]
Can reproduce this issue, but since it is an edge case and @marcelmoosbrugger is currently redesigning this I'd say we just wait. @marcelmoosbrugger should close this issue as soon as the redesign is finished (and if this issue is gone of course)

**Comment by wachterjohannes** [comment]
@marcelmoosbrugger can you check this?

**Comment by nnatter** [comment]
@wachterjohannes this is not an issue on current develop status, because document-saving is handled automatically on document-select insead of toolbar-save now

**Comment by danrot** [comment]
Just checked, can confirm what @nnatter said, so I'll close this issue.
