### ISSUE TITLE
Conflicts were merged on husky.min.js in AdminBundle

### ISSUE THREAD

**Issue by lenardpalko** [sulu-io/sulu#1465]
In the following file the git conflict marker was merged on the develop branch and it is crashing the login page : 

https://github.com/sulu-io/sulu/blob/develop/src/Sulu/Bundle/AdminBundle/Resources/public/js/vendor/husky/husky.min.js

Unfortunately not sure which one is the correct one since the login page works with both versions.

**Comment by wachterjohannes** [comment]
thanks for reporting i have added newest husky version! to be sure that you have a working version you could use the tagged or master version (:
