### ISSUE TITLE
Rest cget-action of accounts errors with a 500 http response code

### ISSUE THREAD

**Issue by marcelmoosbrugger** [sulu-io/sulu#1471]
calling {root}/admin/api/accounts produces the following error
![bildschirmfoto 2015-08-11 um 11 38 24](https://cloud.githubusercontent.com/assets/1998663/9194812/5092e7cc-401e-11e5-9dab-56a60e29319e.png)

I am on the current "dev-develop" branch but also tested it on sulu.burns.at (with version 1.0.2) where its not working either.

**Comment by danrot** [comment]
This only happens if a contact is assigned to the organization.
