### ISSUE TITLE
Can not change a single_internal_link selection once saved

### ISSUE THREAD

**Issue by kriswillis** [sulu-io/sulu#1496]
Using the default Sulu Standard (1.0.7) install:

1. Create and save page with Default page template
2. Create page with Example page template
3. Select page created in step 1 for "Single internal links" input
4. Save page
5. Select magnifying glass icon next to "Single internal links" input with the intention of changing it
6. Empty "Select single Internal Link" modal is shown

When leaving the page editor and then going back to it to edit the Example page, after clicking the magnifying glass icon to change the linked page, an XHR is triggered and the data for the selected page is returned, still, nothing is displayed in the modal for selection.

**Comment by danrot** [comment]
I remember that we had a similar issue with the smart content, but I can't remember the fix...

@wachterjohannes Haven't you fixed it there?

**Comment by wachterjohannes** [comment]
@danrot cannot remember a bug like this! i have to evaluate this next week!

**Comment by danrot** [comment]
Found it: https://github.com/sulu-io/sulu/issues/1274

**Comment by wachterjohannes** [comment]
@danrot seems to be right i will take a look at this!
