### ISSUE TITLE
Shadow Pages returning wrong URL (404)

### ISSUE THREAD

**Issue by thomasduenser** [sulu-io/sulu#1546]
Shadow Pages are returning wrong url which leads to the 404 error.

We've updated two projects:
from 1.0.5 to 1.0.9
from 1.0.6 to 1.0.9

After the upgrade the links were broken for the navigation and smart content pages. Workaround is to use the urls array, for example `page.urls['de-at']` -> seems like the url is correct in the array.

We can't really say since which version this bug exists - but I'm not able to reproduce it with newly created shadow pages. I have a backup of such a project where it can be reproduced.

**Comment by wachterjohannes** [comment]
@thomasduenser can we take a look at this today?

**Comment by thomasduenser** [comment]
@wachterjohannes Of course!

**Comment by thomasduenser** [comment]
This bug is fixed.
