### ISSUE TITLE
Problem with texteditor in Chrome on Windows

### ISSUE THREAD

**Issue by c00n84** [sulu-io/sulu#1547]
If I want to add a link in the texteditor, the overlay appears, but I can't confirm my input. The "OK" button is missing.
<img width="367" alt="bildschirmfoto 2015-09-04 um 09 31 24" src="https://cloud.githubusercontent.com/assets/841720/9678657/cafff4b0-52e7-11e5-9836-a0301a6d52f9.png">

**Comment by alexander-schranz** [comment]
on which version this bug occur? #1457

**Comment by c00n84** [comment]
Ok I see ... in this project we have version 1.0.4

**Comment by wachterjohannes** [comment]
@c00n84 please check this! if its not fixed reopen it!
