### ISSUE TITLE
Problem with PathCleanup and special characters (é, á)

### ISSUE THREAD

**Issue by thomasduenser** [sulu-io/sulu#1548]
We've tried to copy a locale to another and it stopped at a page which had `é` in it's title. The path cleaner can't handle those characters because in the `cleanup` function, **strtolower** returned something like `%A0`.

Instead of this...
````
    $clean = strtolower($dirty);

    $replacers = array_merge(
        $this->replacers['default'],
        (isset($this->replacers[$languageCode]) ? $this->replacers[$languageCode] : [])
    );

    if (count($replacers) > 0) {
        foreach ($replacers as $key => $value) {
            $clean = str_replace($key, $value, $clean);
       }
    }

```

... the **strtolower** should happen afterwards to fix this bug.

$replacers should also be filled with more characters, for example:
````

            'á' => 'a',
            'Á' => 'a',
            'à' => 'a',
            'À' => 'a',
            'é' => 'e',
            'É' => 'e',
            'è' => 'e',
            'È' => 'e',
```

**Comment by danrot** [comment]
Related to #1371
