### ISSUE TITLE
Content Locale Copy doesn't copy the extension Data

### ISSUE THREAD

**Issue by thomasduenser** [sulu-io/sulu#1549]
Seems like there's a bug in the locale copy command with the extension data like **SEO** and **Excerpt**. It doesn't copy them to the destLocale.

In the **ContentMapper** function **copyLanguage** we've added following line in the foreach before `$this->documentManager->persist($document, $destLocale);`:

```
$document->getExtensionsData()->toArray();
```

Afterwards it worked - maybe the extension data must be an array, otherwise persist can't handle the $document?

**Comment by wachterjohannes** [comment]
@berndhep if this should be copied => this should be a HOTFIX! what do you think?

**Comment by berndhep** [comment]
@wachterjohannes Yes, Hotfix
