### ISSUE TITLE
Title in content-edit is always taken from the 'title' property of the data

### ISSUE THREAD

**Issue by marcelmoosbrugger** [sulu-io/sulu#1552]
![bildschirmfoto 2015-09-07 um 14 14 47](https://cloud.githubusercontent.com/assets/1998663/9716525/d3212d3c-556a-11e5-9016-c11e8d9c282f.png)

In the edit of a content-node the title, which gets displayed on top of the form, is always taken from the 'title' property of the data retrieved from the server. This only works if the name of an xml-property in the current template is 'title'.

 A cleaner way to fetch the title from the data would be to somehow construct the title string out of those properties, which have a 'headline'-parameter set to true.

```
<property name="this-is-the-title" type="text_line" mandatory="true">
    <meta>
        <title lang="de">Titel</title>
        <title lang="en">Title</title>
    </meta>
    <params>
        <param name="headline" value="true"/>
    </params>

    <tag name="sulu.rlp.part"/>
</property>
```

**Comment by wachterjohannes** [comment]
@marcelmoosbrugger why do you use here a parameter for that? i would use here a TAG ...

**Comment by danrot** [comment]
I don't see the point in that at all... A template has to have a `title` anyway, since we rely on that a lot...
