### ISSUE TITLE
Blocks are not updated in preview unless they are re-ordered, or one is added / removed from the collection

### ISSUE THREAD

**Issue by kriswillis** [sulu-io/sulu#1582]
Using a fresh install of Sulu Standard:

1. Create a page
2. Select "Example" template
3. Mark as published
4. Enter something in "Textline" so a URL is generated
5. Enter something in "Telefon input" (required)
6. Save
7. Scroll to bottom and enter something in each of the two "Article" blocks (preview updates)
8. Add another block and enter something (preview does NOT update)
9. Add another block (preview DOES update to show the previously added block)
10. Enter something in newly added fourth input (preview does NOT update)
11. Edit third block (preview does NOT update)
12. Edit second block (preview does update, but ONLY the second block)
13. Re-order blocks (preview updates ALL blocks)
14. Reload the preview panel (only first two blocks are shown)
15. Delete a block (preview updates all remaining blocks)

It seems the only blocks that are consistently updated are those that were previously saved and are present when editing the page, and even then, I think it has more to do with their position rather than the actual block, as newly added blocks seem to update if they're moved to the top.

**Comment by wachterjohannes** [comment]
@kriswillis i try at the moment to figure out why this is so strange ... i think its a problem in serialization of preview content (: i have to look a bit deeper tomorow ...

**Comment by danrot** [comment]
Sounds to me like this is a problem with the change detection... We should really try to implement a clean solution here :confused:

**Comment by danrot** [comment]
@kriswillis Thank you for the detailed issue, it helped a lot :smile:
