### ISSUE TITLE
Contact photo upload does not work without collection with id 1

### ISSUE THREAD

**Issue by Quehnie** [sulu-io/sulu#1587]
**Working on develop after 1.0.10**

When i upload a contact photo, it wont work, if i don't have a collection with the id 1.

**Example:**
    When i don't have any collections yet.
    Or when i deleted the collection with id 1, i'm not able to create a new collection with id 1

**Other questions are:**
    Can i only upload images in my contact?
    Why i can't select already uploaded images?

**Comment by wachterjohannes** [comment]
i will fix this with a config but we should really implement the system collections before 1.1 ...

**Comment by wachterjohannes** [comment]
linked issue https://github.com/sulu-io/sulu/issues/1590

**Comment by wachterjohannes** [comment]
we have decided to divide the avatars from other collections and put them in a special collection for "contacts" you can then edit them in the collection view. but you cannot delete them. /cc @berndhep correct me if i´m wrong.

**Comment by wachterjohannes** [comment]
if this is merged you can configure the collection over the config tree `sulu_contact.form.avatar_collection` default its `1`
