### ISSUE TITLE
Content type block, block-type select has colspan 3

### ISSUE THREAD

**Issue by Quehnie** [sulu-io/sulu#1588]
**Working on develop after 1.0.10**

The new block-type dropdown has a colspan of 3, so when i add a property with colspan 9 or less it will go into the same line.

![textblock colspan issue](https://cloud.githubusercontent.com/assets/8446502/9907847/4ba37a62-5c91-11e5-8535-6dc0083a9100.png)

**Comment by wachterjohannes** [comment]
@berndhep is this in your purpose?

**Comment by wachterjohannes** [comment]
this select should be the only element in row one ...
