### ISSUE TITLE
System Collection

### ISSUE THREAD

**Issue by wachterjohannes** [sulu-io/sulu#1590]
Each bundle should be able to create a "System Collection" to put there assets. for example the "avatars" in contact bundle.

**Comment by wachterjohannes** [comment]
structure:

* System-Collections
  * Media
  * Contact
  * ...

Specifications:

* Collection can not be deleted or edited.
* Media can be edited and removed - unlink to other entities like contact or accounts (avatar)

**Comment by alexander-schranz** [comment]
I would say not only foreach bundle e.g. maybe a system collection for contacts and one for organisation which are both handled in the contact bundle there will be also be other cases where it make sense to have multiple system collections for one bundle. 

Did talk about this with @chirimoya and @marcelmoosbrugger.

I would maybe extend the collection with a key so you can load a collection by key -> `getOrCreateCollectionByKey('contact')`.

**Comment by danrot** [comment]
Related to #1587
