### ISSUE TITLE
Twig path on website route will error in sulu preview

### ISSUE THREAD

**Issue by alexander-schranz** [sulu-io/sulu#1610]
if i have a route which I want to return in twig with

``` twig
{{ path('my_custom_route`) }}
```

it will error in the preview because the route is only registered in the website kernel not in the admin kernel.

**Comment by alexander-schranz** [comment]
related #771

**Comment by danrot** [comment]
@alexander-schranz Isn't that even the exact same issue? Then I would say this could be closed as duplicate of the other, couldn't it?

**Comment by alexander-schranz** [comment]
added the problem with the routes to the #771 issue and will close this
