### ISSUE TITLE
Exception when deleting PHPCR content containing Categories

### ISSUE THREAD

**Issue by stemod** [sulu-io/sulu#1635]
When deleting custom entities from database, at "flush" call to entity manager the following exception is thrown:
           "An exception occurred while executing 'INSERT INTO ca_category_translations (translation, locale, idCategories) VALUES (?, ?, ?)' with params [null, null, 2]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1048 Column 'translation' cannot be null"

Like discussed the code is there:
Class: Sulu\Bundle\CategoryBundle\Api\Category
Line: 355

See also: #1556

**Comment by wachterjohannes** [comment]
seems to be duplicated @stemod i will close this issue
