### ISSUE TITLE
Search tries to index Object instead of ID from CLI with custom document type.

### ISSUE THREAD

**Issue by dantleech** [sulu-io/sulu#1636]
If I understand correctly:

- @stemod has created a new structure type, based on the Snippet document type, which has a Category field.
- When saving in the admin, the category is correctly updated.
- When reindexing the search from the CLI, it throws an error because the relation is an object and not an ID.

**Comment by dantleech** [comment]
I am not sure how a category object could be hydrated from the document.

The search reindexer for the content [finds](https://github.com/sulu-io/sulu/blob/develop/src/Sulu/Bundle/ContentBundle/Search/EventListener/ReindexListener.php#L91) the document. The category value is determined by the `CategoryList` content type, it hydrates the categories as [an array](https://github.com/sulu-io/sulu/blob/develop/src/Sulu/Bundle/CategoryBundle/Content/Types/CategoryList.php#L78) which might have something to do with your problem.

But I can't see how an object is being hydrated. Can you post the exception and your object in a [gist](https://gist.github.com).

/cc @danrot @wachterjohannes

**Comment by danrot** [comment]
Acually @stemod has to do that, he gets that error.

**Comment by stemod** [comment]
@dantleech
we granted you access to the project - see email for details.

**Comment by dantleech** [comment]
I havn't checked out the project yet, but I have just tested the following:

1. Add the `category_list` content type to a snippet
2. Edit the snippet and assign a category to it.
3. Rebuild the index.

This worked without any problems. How is your use case different?

I will try and check out your project tomorrow or at the weekend.

**Comment by dantleech** [comment]
Have discussed with @stemod on Slack. Problem is that the ContentType for the Category writes an array of IDs but reads an array of objects. This is a known issue that will be addressed when we refactor the content system.

For this to be resolved we need to add a way to:

1. Handle arrays (i.e. Elastic search has a dedicated type, with Zend Search we need to use a string).
2. Handle the indexing differently if the value is an array of objects or an array of integers, which requires:
3. Support for specifying expressions in the `sulu.search` tag and ..
4. A way of forking behavior based on the value type.

Points 3 and 4 might change.

**Comment by danrot** [comment]
That still doesn't explain to me why it is indexed differently. Are the content types used in one environment, and in the others they are not?

**Comment by dantleech** [comment]
Because the content types "read" for the display and are written to from the request. Thus "reading" the category list returns an array of array's (category->toArray) and after saving in the UI the value is an array of IDs. This is a fundamental issue with the current content layer.

**Comment by dantleech** [comment]
One way to work around this problem for now is as follows:

- Create a function in the `massive.search.expression_language` which handles the category values.
- Use an expression to index the field value:

````xml
<property name="foo" type="category_list">
    <tag name="sulu.search.field" expr="categories_to_array(object.getStructure().getFoo())" />
</property>
````

For this you will need the following PR's:

- Allow expressions in the search tag: https://github.com/sulu-io/sulu/pull/1672
- Allow indexing of arrays in MA search bundle: https://github.com/massiveart/MassiveSearchBundle/pull/60

You should add the functions to the expression language using providers, see here:

http://symfony.com/doc/current/components/expression_language/extending.html#using-expression-providers

**Comment by dantleech** [comment]
The PR's above will probably need some attention and I will not be around very much to attend to them, so please feel free to take them over or wait for an undetermined amount of time.

**Comment by wachterjohannes** [comment]
@danrot @chirimoya we have to talk about who finish this PR.

**Comment by danrot** [comment]
@dantleech Wouldn't it make more sense for the current problem to use an expression like the following:

```xml
<tag name="sulu.search.field" expr="map(object.getProperty('foo'))"/>
```

And for me it is also questionable to add this feature. It feels a bit strange to me, to add this to the property, since it might also be possible to put some nonsense in there. This might end up very confusing...
