### ISSUE TITLE
Apply security on the search

### ISSUE THREAD

**Issue by danrot** [sulu-io/sulu#1637]
Currently the search does not apply the security attached to the current user when returning the results. This means that the search result also contains items, which the user is actually not allowed to see.

The search should therefore also consider the security settings of Sulu. The short paragraph in http://docs.sulu.io/en/latest/bundles/security.html#checking-security explains a bit how that works, although a piece of code would also be nice in that place.

There are two possiblities solving this:
* filter the search results in the controller
* additionally index the security information and add that to the search criteria

The first approach would be quite easy, but makes pagination almost impossible. Adding the information to the search index means that the security logic might have to be repeated (not sure if there is an elegant way around this).

**Comment by danrot** [comment]
@chirimoya just mentioned that we already agreed to save all the roles as an array, which have a view permission on the given item. This way it should be quite easy to filter that in elastic search, for Zend Lucene we have to find a solution.

But first it would be important to only search through the indexes the user has a permission according to the security context.

**Comment by dantleech** [comment]
>> But first it would be important to only search through the indexes the user has a permission according to the security context.

Do we really need to do that if we are already flltering the search documents based on role?

>> ... for Zend Lucene we have to find a solution.

Without checking I think it should be possible to store the roles in a delimited list .. which would be made easier if it were illegal for roles to have spaces in them, as we can then seach for an exact single word match. Otherwise I expect we would have to create a new Tokenizer or something.

---

For the approach, I think we could build this feature directly into MassiveSearchBundle. We could add a "security contexts" field to the `SearchQuery` class, and then delegate the logic to the adapters.

**Comment by danrot** [comment]
Somehow you are right, if the security information is saved in the index, it would not be necessary to only search the right indexes. But it is hard to keep this information up to date, so if the security on a role changes this also has to be updated in the index. Maybe also ask @chirimoya, as it was his idea to filter by indexes at first.

Using a delimited list in Zend Lucene sounds good to me. Keep in mind that roles can have spaces in it, there is already an issue with that: #1616

**Comment by dantleech** [comment]
> But it is hard to keep this information up to date, so if the security on a role changes this also has to be updated in the index

Hmm, yes, didn't think of that. That would be a real pain, but maybe worth the sacrifice /cc @chirimoya 

> Keep in mind that roles can have spaces in it, there is already an issue with that

So are we saying that it is illegal to have spaces in a role? Using a space as a delimiter in Zend Lucene would at best be easier, using a different character would be an unknown problem.

> And do you really want to include that into the MassiveSearchBundle?

Well .. it would be easier and probably better. The main issue is how the adapters handle the storage and searching of roles. I think branching out here (basically creating an event subscriber for every adapter) would not be desirable. We can instead "ship" MassiveSearchBundle with security built-in.

It is a Symfony Bundle and it will be implementing Symfony security (i.e. Roles).

**Comment by dantleech** [comment]
Have had a think about this and I do not think it would be practical to store the permissions in the object:

- ACL is done on a per-user per object basis -- we cannot store that information in the search document

This leaves us with no choice but to filter the results aftwerwards, which as @danrot mentioned, makes pagination difficult. I have two proposals:

1. We do not remove the entries in the search results, instead we "grey them out" (and add a padlock icon). In most cases it is more user friendly as the user knows that the record exists and that they do not have access to it, so they can then take further action such as asking the relevant person for access.

2. We iteratively search until we have the required number of non-restricted records. This could be expensive, especially with the ZendLucene implementation. The effect could be mitigated by always searching for 2x the number of records that we require.

I prefer #1. To me it makes sense from a user POV - except in the case where the existence of a document must be concealed, but as a user I would prefer to know that a document exists and that I don't have access to it for reasons explained above. It is also the most performant and simple option.

/cc @berndhep (see #1)

**Comment by danrot** [comment]
@dantleech I have discussed with @chirimoya yesterday, and we concluded that for the next release it would be enough, if just the indexes are search, for which the user has the permission based on the security contexts, and that objects which have role based permissions are ignored at the moment.

We also agreed that this logic should not be in the MassiveSearchBundle, since it should also be usable with other security systems not relying on roles. But this is now a separate issue, since the indexing of the object as said before is done in Sulu anyway, right?

**Comment by dantleech** [comment]
Maybe we should talk tomorrow, I should be around.

Not sure how the index security you propose would work, and as said I
would prefer to do the easiest thing and show items the user does not
have access (with a locked icon and no link) to in the results, and if
that is not enough maybe to iteratively seach until the requisite number
of results is obtained.

But lets talk tomorrow.

**Comment by danrot** [comment]
Why should the index security not work? It would even work quite easily, because each index corresponds to a single security context.

I don't think that just greying items out is a good solution. The security should be really secure, and if I don't want to see anyone a document, even the title is usually too much.

Iteratively searching is a real pain, and in certain cases it could be very slow. The proposed solution is the easiest, and should be implemented.

**Comment by dantleech** [comment]
The fact that there is an index per security context is an implementation detail. It is not something, for example, that we even need to do in Elastic Search. Sulu should not know that there is an index per-structure type. But we could provide an interface to specify security "roles" to indexes in massive search.

````php
$manager->createQuery('My Hidden Document')->locale('de')->roles($user->getRoles());
````

**Comment by danrot** [comment]
That's exactly what we don't want, since it couples the MassiveSearchBundle to the concept of roles. As I already said, this is not acceptable for me.

And that there are separate indexes is not an implementation detail, you can also search for single indexes in the search (the blue dropdown). Could be that this is solved with categories, but then you should be able to do simple the same for the search over the entire system. Just pass the categories for which the user has the view permission in the corresponding security context.

**Comment by danrot** [comment]
@dantleech What would you think about introducing some options to the XML file? Would make it a lot easier to add some customization, without adding another XSD file, and extend the parser. Especially for this use case I would favour something like the following:

```xml
<?xml version="1.0" ?>
<massive-search-mapping xmlns="http://massiveart.io/schema/dic/massive-search-mapping">
    <mapping class="Sulu\Bundle\MediaBundle\Entity\FileVersionMeta">
        <id property="id" />
        <title property="title" />
        <description property="description" />
        <index name="file_version_meta" />
        <category name="media" />
        <locale property="locale" />

        <fields>
            <field name="title" type="string" />
            <field name="description" type="string" />
        </fields>

        <options>
            <option name="security_context">sulu.media.files</option>
        </options>
    </mapping>
</massive-search-mapping>
```

**Comment by dantleech** [comment]
Another option would be to lever (again) the expession language:

````xml
<... expr="sulu_has_security_context('sulu.media.files')" />
````

Also this security context applies directly to the index? Maybe it would simply be better to have this data defined in the DI config.

I.e. it is valid to have two or more mappings in the same index.

So I might define this in the DI config:

````yaml
sulu_search:
    index_security:
        <index-name>
            roles: [ sulu.media ]
        ...
````

(just ideas)

**Comment by danrot** [comment]
I am already thinking in a bigger scope, if we add something like you have suggested with the expression language, we have to add another tag for that (and I still don't want the security to be part of the search bundle). Having options would also enable other developers to add some configuration to these files.

I have added to options to the mapping in the example, because they apply to the entity. As long as we only have one entity per index it doesn't matter, but I would prefer to do that the right way.

The security is until now also defined by the bundle itself, so I would make no exception for the search. This might just lead to misconfiguration. If the user is not allowed to see the entity, the bundle shouldn't show it to him, regardless of the configuration of the application.

**Comment by dantleech** [comment]
Can we aggree that the problematic is:

````
Retrieve the index names to search for a given set of security contexts
````

**Comment by danrot** [comment]
I would say return the category names... Well, I would say it depends on how you actually use it. I don't really get the difference between indexes and categories at all.

**Comment by dantleech** [comment]
Following our discussion on slack I understand that you will add `<options/>` to the MassiveSearchBundle and search for specifc categories from the SearchController until a later time when we can apply more fine grained permissions (e.g. on individual mapped classes).

We should also consider how to reuse the existing security mappings in the future (should we simply add mappings for indexed classes which are not mapped in the security system to the security system?).
