### ISSUE TITLE
Content tree is showing shadow pages on page exit

### ISSUE THREAD

**Issue by Quehnie** [sulu-io/sulu#1647]
Hey Sulu Team,

since i last updated to the latest dev-develop version, a new bug occours. Looks like if i enter a contentpage and exit it over the sulu back button, all pages under that tree look like shadow pages.
After switching to another tree and back everything is normal again. I dont change the language or something like that.

![bildschirmfoto 2015-09-30 um 16 08 42](https://cloud.githubusercontent.com/assets/8446502/10216917/c29c31c6-682c-11e5-96e6-55cc439eeac7.png)

![bildschirmfoto 2015-09-30 um 16 09 21](https://cloud.githubusercontent.com/assets/8446502/10216925/c87a9a7e-682c-11e5-9fb3-417793598771.png)

**Comment by wachterjohannes** [comment]
@berndhep this doesn`t happen within the master branch therefor this is no HOTFIX.

**Comment by wachterjohannes** [comment]
the PR from @dantleech https://github.com/sulu-io/sulu-document-manager/pull/46 should fix this issue
