### ISSUE TITLE
Show / Hide Shadowpage Button doesn't work like expected.

### ISSUE THREAD

**Issue by Quehnie** [sulu-io/sulu#1648]
Never Hides Shadow page, maybe it occours with the other shadowpage bug.
https://github.com/sulu-io/sulu/issues/1647

![bildschirmfoto 2015-10-01 um 11 11 37](https://cloud.githubusercontent.com/assets/8446502/10217010/66fabd82-682d-11e5-8829-c73e79f3134e.png)
![bildschirmfoto 2015-10-01 um 11 11 29](https://cloud.githubusercontent.com/assets/8446502/10217013/6b33fdbe-682d-11e5-96ab-7d4086b06b21.png)

**Comment by danrot** [comment]
I am quite sure that these bugs are connected, so probably both issues can be closed once it is fixed.

**Comment by wachterjohannes** [comment]
no this are not connected! the state of the button is not implemented correctly in the form!
