### ISSUE TITLE
Filter cannot be deactivated when no results are found

### ISSUE THREAD

**Issue by turbo-ele** [sulu-io/sulu#1657]
When you filter a list and no results are found, there is no way for disabling the filter:
![image](https://cloud.githubusercontent.com/assets/5152633/10307458/83c3b4cc-6c2f-11e5-8302-1b7dac2b1fce.png)

the result toolbar is missing:

![image](https://cloud.githubusercontent.com/assets/5152633/10307486/b8a0c752-6c2f-11e5-8f8f-ec22a41ce39a.png)

**Comment by danrot** [comment]
What's the "x" on the right side of the label doing?

**Comment by turbo-ele** [comment]
exactly this toolbar is MISSING (not displayed)

**Comment by berndhep** [comment]
@oliverpretz Please coordinate this in your team. We can only consult.
