### ISSUE TITLE
200 Items on search result page not clickable

### ISSUE THREAD

**Issue by oliverpretz** [sulu-io/sulu#1662]
The items on the search result page are not clickable (e.g. contacts):

![bildschirmfoto 2015-10-07 um 07 56 03](https://cloud.githubusercontent.com/assets/1152516/10330111/631c5716-6cc9-11e5-97e2-312add184e72.png)

**Comment by wachterjohannes** [comment]
media has also no link to the edit form! content is linked but on the first look the route seems to be wrong (could also be a problem of data on my local machine) i will look at this deeper
