### ISSUE TITLE
Delete old files from media collections

### ISSUE THREAD

**Issue by lennerd** [sulu-io/sulu#1679]
When files are deleted in the backend, they are not removed from the default `uploads/media' folder.

Did I miss some configuration/option to turn this on? Or is this intended to work like this?

PS: Guys, I wonder why never came across your great work of software. You thought about so many great things and the interface is gorgeous – especially in comparison with other stuff out there. Thank you for making such great software free to use for everyone!

**Comment by wachterjohannes** [comment]
@lennerd thanks for compliment (: i will try this out today! but actually it should delete the file from `uploades/media`.

**Comment by wachterjohannes** [comment]
this files wont be deleted ... i think its really a bug!

**Comment by lennerd** [comment]
Can I help fixing this? Where should this be handled?

**Comment by wachterjohannes** [comment]
an idea is to look why the function `LocalFormatCache:purge` dont works (:

**Comment by lennerd** [comment]
That's a direction. :wink:  If needed or helpfull I can take a look into this later this day.

**Comment by wachterjohannes** [comment]
that would be cool! maybe then we can include it into 1.1

**Comment by lennerd** [comment]
I really would like to make a PR for this, but I have problems setting up my testing environment (damn you have made it complicated :stuck_out_tongue_closed_eyes:).

Can you give me another hint where I can configurate the jackalope configuration for running the tests? I need to set another port.

**Comment by lennerd** [comment]
While trying to wrap my head around the of Sulu test folders, I wonder about your general strucutre of Components and Bundles.

First of all, I try to understand why there is a tests directory in the root folder. I see that you store some configuration and kernel there. But why not putting tests inside the components folder like symfony does? So that you have tests inside the bundles testing the bundles and tests inside the components testing the components?

Then I wonder why we some of the classes are stored in component folders, others are stored in bundle folders. It's hard to guess for example where a content type class would be as the `TextEditor` class is inside `Component\Content` and `SingleInternalLink`can be found in `Bundle\ContentBundle\Content`?

Maybe this discussion needs to take place in another issue, but maybe you have some resources or old discussion where I can get some insides?

**Comment by wachterjohannes** [comment]
we like to say its "historically arisen"! we recommend you to use IntelliJ or PHPStorm where you can easily search for class names. We have some "old" classes from the time we implement all the stuff in the bundles. But we have learned in this time to create more and more components. but we didn't have time to migrate the old stuff ... but yeah i think we can discuss in a new issue if we restructure the tests in a new issue and i think the migration of bundled classes should be triggered maybe right after 1.1 release. /cc @danrot what did you think?

**Comment by wachterjohannes** [comment]
@lennerd why do you need to change the port of jackrabbit?

**Comment by wachterjohannes** [comment]
you can change the settings of phpcr for the component tests under `app/config/config.yml` and i think the same should work for each bundle ... dont forget to reset it before commiting (:

````
sulu_core:
    phpcr:
        backend:    "%phpcr_backend%"
        workspace:  "%phpcr_workspace%"
        username:   "%phpcr_user%"
        password:   "%phpcr_pass%"
```

**Comment by danrot** [comment]
I'd love to restructure all of this, but it is far too much work, and a huge BC break, so I guess that won't work before 2.0.

**Comment by lennerd** [comment]
:see_no_evil: Sure, there are configuration files. I think it was to late yesterday. Hope I was not sounding arrogant.

@wachterjohannes I need to change the port because 8080 is used by my development server. I'm not quite sure which options I change the port with.

Talking about configuration files, could we maybe use `ENV` variables to handle such configuration concerns? This way we can pass options to the phpunit or other commands and don't need to touch the configuration files.

> I'd love to restructure all of this, but it is far too much work, and a huge BC break, so I guess that won't work before 2.0.

Maybe this sounds crazy, but we could use dump classes to prevent BC breaks. Classes which fire a deprecation warning in the constructor and which only extend new classes in the components folder. But maybe this to much.

**Comment by danrot** [comment]
Yeah, that doesn't sound too bad, but would probably still be a lot of work :smiley:

**Comment by wachterjohannes** [comment]
hmm the idea with ENV variable sounds quite good! maybe we could define default values if ENV is not set ... then it would be really nice (:

**Comment by danrot** [comment]
Actually we already use that for some kind of stuff (there are already environment variables `SULU_PHPCR` and `SULU_ORM`, which are required to run different jobs on travs). Guess it would also be ok to apply this to other configurations.

**Comment by lennerd** [comment]
Okay, so this sounds like a complete different issue. I would like to open a new one for this, but I'm not sure, what focus it should have. "Making tests portable"?

> Yeah, that doesn't sound too bad, but would probably still be a lot of work :smiley:
I put some more thoughts in this and realized, that the dependency management would possibly break code if somebody uses refactored services and try to check for instances of old classes. Maybe there are other scenarios.

**Comment by danrot** [comment]
Well, as said, I think there is no way around a BC break, so I would say we just wait with that. But moving the tests should be fine, although it also might confuse people when this changes, but at least the application would still work.

The other advantage of this would be to actually test the dependencies between the bundles and components. Currently always all bundles are loaded, so we don't know which bundle is dependent on what.

How about "Move tests to correct component" as title?

**Comment by lennerd** [comment]
I was thinking about a title for the "server port for jackalope" issue. Working on both in one PR could be to much, couldn't it?

**Comment by danrot** [comment]
Ah, I see... Then I would suggest "Use environment variables for test configuration".

**Comment by lennerd** [comment]
Sounds fantastic. I will try this.

Is this still reliable for testing locally? https://github.com/sulu-io/docs/blob/master/developer-documentation/000-foundation/testing.md

**Comment by danrot** [comment]
I think so, yeah.

**Comment by lennerd** [comment]
Okay, cool. I make a PR for this when #1689 is fixed.
