### ISSUE TITLE
Missing reset functionality for single_internal_link properties

### ISSUE THREAD

**Issue by lennerd** [sulu-io/sulu#1680]
Hey everbody,

me again. I wonder if it's possible to have a title for links comming from a `single_internal_link` property which is not the title of the linked page?

Further more it would be nice to be able reset a value inside the form field of `single_internal_link`.

Did I miss something? Thanks in advance for your help!

**Comment by danrot** [comment]
The `single_internal_link` content type just links to another page. If you want to have a different title than anything from what is managed in the linked page, you have to add another type, probably a `text_line`. You could also group these fields using a block.

And yeah, I think the resetting functionality is missing in some places :confused:

**Comment by lennerd** [comment]
I managed to do this with snippets. Working quite well and I'm able to have multiple links with titles. :smile:

Should I leave this open regarding the missing resetting?

**Comment by danrot** [comment]
I personally would prefer to have this on the page instead of snippets, but if it works for you it is fine :smiley:

Yeah, you can leave it open, but please change the title accordingly.
