### ISSUE TITLE
Use environment variables for test configuration

### ISSUE THREAD

**Issue by lennerd** [sulu-io/sulu#1689]
As discussed in #1679 we need some easier way to change important configuration for testing on local machines.

My personal use case would be to change the port of the jackrabbit server, because I use 8080 in my local environment setup.

**Comment by dantleech** [comment]
This is already possible in Symfony: http://symfony.com/doc/current/cookbook/configuration/external_parameters.html

**Comment by lennerd** [comment]
Thanks for the link. :+1: That helps a lot.

Von meinem iPhone gesendet

**Comment by lennerd** [comment]
While fixing this bug, I ran into "Too many open files" error, when running the test suite. Why do we have logging for tests? Is this intended?

**Comment by wachterjohannes** [comment]
i have also had this issue ... maybe just disable it? i cannot think that it is helpfully to have a log of the tests.

**Comment by danrot** [comment]
Do you have xdebug enabled? I encounter this issue a lot, if my installation is running with it.

But you are probably right, we should be able to disable logging... Probably makes the tests even faster again :smile:

**Comment by danrot** [comment]
Couldn't resist, was too curious: https://github.com/sulu-io/sulu/pull/1698 :smile:

**Comment by danrot** [comment]
According to tests on my locale machine the tests are running 5-15% faster, depends on how exhaustive the logging is used in the suites.

**Comment by danrot** [comment]
But it doesn't help too much with the too many files open error, which makes sense if you think about it... It is only one file per bundle.
