### ISSUE TITLE
Add "easyfix" label for beginner issues

### ISSUE THREAD

**Issue by lennerd** [sulu-io/sulu#1707]
Add a label for easy fixes (something like `easyfix`, `beginner`, `mentored` etc.) to encourage new contributors to participate. This way someone who wants to learn and contribute to the software knows where to start.

**Comment by patkar** [comment]
`easy pick` is usually used, e.g. in symfony :)

**Comment by chirimoya** [comment]
There is already a label `easy pick` https://github.com/sulu-io/sulu/labels/easy%20pick
