### ISSUE TITLE
Documentation property SmartContent

### ISSUE THREAD

**Issue by Quehnie** [sulu-io/sulu#1738]
the parameter `website_categories_operator` is actually `website_category_operator`,

the question is both in plural or not, so change in code or in documentation?
website_tags_operator
website_categories_operator

**Comment by wachterjohannes** [comment]
i would change it in code @danrot what did you think?

**Comment by danrot** [comment]
Since the operator requires at least two categories to make sense I would also say plural, but this name is not too important for me.
