### ISSUE TITLE
Property "url" in structure "default" is required but no value was given.

### ISSUE THREAD

**Issue by c00n84** [sulu-io/sulu#1765]
I wanted to change a page from external link to default content page. I think the error occurs because the tab for content is missing.

**Comment by danrot** [comment]
Happens also when the page was an internal link

**Comment by danrot** [comment]
It's also a duplicate of #1674, which is tagged to version 1.2, should that be solve before? However, the fix suggested there, is probably not too easy to implement.

**Comment by berndhep** [comment]
@danrot 1.2 or Hotfix.

**Comment by c00n84** [comment]
Fact is, that when a client want to change a page from external or internal link to a standard content page, he gets an error. I solved it by deleting the page and create a new one
