### ISSUE TITLE
Thumbnailview Large not found after update

### ISSUE THREAD

**Issue by alexander-schranz** [sulu-io/sulu#1768]
After update to 1.1 you can't access a collection when your last view was thumbnailLarge. 

It will try to load a none exist `/bundles/suluadmin/js/thumbnailLarge.js` and throw an 404 error. 

We should add to upgrade.md to remove all `userSettings` media views.

**Comment by danrot** [comment]
@alexander-schranz Haven't you described that in #1770 ?

**Comment by alexander-schranz** [comment]
@danrot yes

**Comment by danrot** [comment]
Then you should also write that in the PR :wink: I'll do that for you.
