### ISSUE TITLE
Video Preview Rendering

### ISSUE THREAD

**Issue by stemod** [sulu-io/sulu#1803]
Filenames with umlauts have problems to render previews on UBUNTU.

e.g.: filename with "füllung" is shortened to "fllung".

**Comment by danrot** [comment]
Sounds like a encoding issue on the server to me. Also found this comment in the php manual: http://php.net/manual/de/function.escapeshellarg.php#99213

**Comment by danrot** [comment]
Umlauts will be escaped in the filename now.
