### ISSUE TITLE
Sulu contact images resolution

### ISSUE THREAD

**Issue by Quehnie** [sulu-io/sulu#1838]
In the new update sulu contact images are now oval. The div they are set as a background has a size of 159x98 but the image only has 100x100 so it's really blurred.

Greets Quehnie

**Comment by chirimoya** [comment]
@danrot @wachterjohannes please check.

**Comment by danrot** [comment]
Was caused by this commit: 40cec602f26f72250e66b790cc9c99d6d689e845 @wachterjohannes Why did you change that?

**Comment by wachterjohannes** [comment]
because the title was so short ... otherwise we have to crop it to short ... maybe i have overseen the sideeffect!
