### ISSUE TITLE
Pagination in a collection is not working properly for multilingual asset titles

### ISSUE THREAD

**Issue by sabinebaer** [sulu-io/sulu#1860]
Example:
I have a collection with 109 files, every file has its title translated to 6 languages. If I switch to the collection in the Sulu Admin it shows me "Items per page: 4". If I change the items per page to 50, the drop down shows "Items per page: 9" and 9 items are shown.

It seems that the query to fetch the asset is missing a limitation on the language.

**Comment by wachterjohannes** [comment]
@sabinebaer we have already fixed that in the newest HOTFIX release https://github.com/sulu-io/sulu-standard/releases/tag/1.1.1 could you please check if it is really fixed? if not reopen this issue
