### ISSUE TITLE
Excerpt tab doesn't show on internal and external link content type

### ISSUE THREAD

**Issue by danrot** [sulu-io/sulu#1870]
Currently the excerpt tab is not shown if the selected content type of a page internal or external link, like shown in the screenshot:

![image](https://cloud.githubusercontent.com/assets/405874/11741331/9948e6f8-9ff8-11e5-9a37-e4fb1e8fb572.png)

This might also be useful for external links, so that they can be assigned a tag or category and e.g. also be shown on the startpage using the smart content.

**Comment by danrot** [comment]
@berndhep WDYT?

**Comment by wachterjohannes** [comment]
this could easily be realized after merging this #2099 new feature but it has to be decided @berndhep @chirimoya @danrot should i display it when internal or external link is chosen?

**Comment by danrot** [comment]
I'd say yes, but I am not the one to decide that :-)

**Comment by wachterjohannes** [comment]
excerpt displayed only when external link is selected

**Comment by danrot** [comment]
And also for the content page type ;-)

**Comment by wachterjohannes** [comment]
For content type all tabs
for internal link / shadow only settings and permission
for external link excerpt, settings and permissions
