### ISSUE TITLE
Media type can change with a new file version

### ISSUE THREAD

**Issue by sabinebaer** [sulu-io/sulu#1889]
It is possible to add a new file version with an other media type than the old file version. Either this should not be possible or the media type should belong to the file version instead of the media.

**Comment by alexander-schranz** [comment]
Thats right seems it was lost in some refractoring. The `InvalidMediaTypeException` should be thrown.

**Comment by wachterjohannes** [comment]
@chirimoya @webmozart @danrot what should we do here? if we want to be able to adapt the file-type we should move this relation from the media to the file. but i think this will be a "bigger" refactoring. in my opinion this should currently not be possible for 1.2 afterwards we can think about the refactoring later.

**Comment by alexander-schranz** [comment]
@wachterjohannes the media type should never change. an image should not become an document or a video. do not confuse it with the mime type and image can change from png to jpg. Ah document from pdf to doc. But as a video is embedded in the content a new version of the video should not be a document. So their is just a check missing old mediaType should be new mediaType else throw the `InvalidMediaTypeException`.

**Comment by danrot** [comment]
I agree with @alexander-schranz. You should also think about the media selection content type. If you allow the media type to change, it would be possible to have an image assigned to a page with a media selection only allowing videos.

**Comment by wachterjohannes** [comment]
then we agree to throw an excepetion?
