### ISSUE TITLE
Question : Workspace

### ISSUE THREAD

**Issue by cbastienbaron** [sulu-io/sulu#1910]
Hi all and Happy New year ! ,

For a project, i need a functionnality like `release` concept at the https://prismic.io/ way.
For example : clone homepage to workspace / release 'HappyNewYear2016' and a front API call homepage for release/homepage HappyNewYear2016 
I've seen somewhere (issue or forum ...) , workspaces have been abandonned / suspended for sulu. 
So my question is : are you been interested by such functionnality ? Have you some advices, guidelines for such functionnality ?

**Comment by wachterjohannes** [comment]
we are currently planning to implement a content-workflow. maybe @berndhep can tell you more about that! perhaps thats enough for you.

**Comment by danrot** [comment]
I don't really get what you mean by front API call. What's the expected end result? Do you want to have happy new year wishes on every single page? Do you have a link to the prismic io documentation describing that feature? Didn't find anything in a quick research.

**Comment by cbastienbaron** [comment]
Hey thks for you're time,

in a nutshell, we have admin sulu for contributors, and a front's api to get the content. (ex: GET /api/v1/homepage) etc. Behind the scene, the idea is : 

i'm contributor, i prepare a release (clone pages, media and stuff into workspace other than `default`). This contributions are not visible into `default` so not for public production.
 
For see my changes i'm going to front website, changing the release i want to see (authentication and stuff) and it's visible only for me.

Perahp's the simplier is to clone a webspace (ex sulu_io to sulu_io_happy_new_year) ? 

for documentation of prismic, there is 
https://developers.prismic.io/documentation/content-publishers-manual#managing-releases 
or php-sdk 
https://github.com/prismicio/php-kit

Hope i'm enough clear (french native .... :) ) ?

**Comment by danrot** [comment]
@cbastienbaron The publishing process is one of the next features we are going to implement. However, it doesn't go as far as prismic.io, for the beginning there will only be a single draft of your website, which can be published at any time.

Versioning is also planned, but we have only thought about versioning single pages yet. And it will probably be released some time after the publishing workflow, but I can't tell you any due date yet.

Having two separate webspaces might work, but would probably include some manual steps done by a developer.

**Comment by cbastienbaron** [comment]
ty for the responses :+1:  yes versionning is also a requirement :smile: 
For versionnning there is some WIP already started ? how do you see this ? in tab extension for exemple ? i can plan some times to work on it if needed

**Comment by danrot** [comment]
Sry if I haven't been clear, both, versioning and publishing, is not started yet. I guess before we really can start to work on that we need to discuss some more details and we probably should also have a finished design /cc @chirimoya @berndhep

**Comment by cbastienbaron** [comment]
nop very clear ;) let's keep us informed

**Comment by danrot** [comment]
@chirimoya Shouldn't we even close this issue? If @cbastienbaron is still interested in this feature, he can subscribe one of the other issues.
