### ISSUE TITLE
Style-CI Update: unnecessary parameter default value

### ISSUE THREAD

**Issue by wachterjohannes** [sulu-io/sulu#1914]
How should we handle default values of parameters which are are not "the rightest ones".

https://styleci.io/analyses/8wEdZq

Style-CI seems to be updated with a feature to fix this parameters and remove the default value. should we go this way and remove them? this seems to be the "rightest" way because this default values has no effect on the code.

But i think the developer which has added this values has some intentions. so where can we define some "example" data - phpdoc for example but in which format should we do it there?

I have created a PR with the resolved style-ci patch <https://github.com/sulu-io/sulu/pull/1913>

**Comment by danrot** [comment]
Merged the PR #1913, is resolved now.
