### ISSUE TITLE
No route found for "GET /admin/undefined"

### ISSUE THREAD

**Issue by seb2411** [sulu-io/sulu#1925]
I just installed and configured Sulu. So it seem to be a really nice CMS on Symfony. But on the admin when I try to login I get this routing error : No route found for "GET /admin/undefined" (from "http://www.nydomain.dev/admin/login")

**Comment by wachterjohannes** [comment]
@christianbader has the same problem a few days ago maybe he could help you

**Comment by wachterjohannes** [comment]
which version of PHP do you use? can you open the admin when you type in the route directly?

**Comment by seb2411** [comment]
Thank you. I'm currently using PHP 5.6 and I can't go to any other page of the admin even directly. In fact I can put any Login and Password and the system show me the animation with the green check and redirect after that to this error.

Looking a little bit further I got some Session errror on my logs. 
```
request.CRITICAL: Uncaught PHP Exception RuntimeException: "Failed to start the session because headers have already been sent by "" at line 0." at /var/www/html/app/cache/admin/dev/classes.php line 114 {"exception":"[object] (RuntimeException(code: 0): Failed to start the session because headers have already been sent by \"\" at line 0. at /var/www/html/app/cache/admin/dev/classes.php:114)"} []
```

**Comment by danrot** [comment]
@christianbader @notsure Have you also got an error like this? That would actually mean we are leaking some whitespace anywhere, but then everybody should experience that problem.

@seb2411 Can you be a bit more specific about the PHP version? I think we only have seen this problem on 5.6.16 until now.

**Comment by seb2411** [comment]
It's the 5.6.16. I get it from the PHP docker image : https://hub.docker.com/_/php/
Do you thin updating to 5.6.17 will work better ?

**Comment by wachterjohannes** [comment]
could you try to update your PHP (: maybe it helps.

**Comment by seb2411** [comment]
Same problem.

**Comment by danrot** [comment]
Can you try to run `php app/check.php` to see if you have some wrong settings in the php.ini?

**Comment by seb2411** [comment]
```[OK]  Your system is ready to run Symfony2 projects```

**Comment by chirimoya** [comment]
Can you provide the whole app/logs/admin/dev/dev.log as gist?

**Comment by seb2411** [comment]
I just tested with Php 5.5.31 and is working in some way. I can access the admin panel but each time I go from a page to another i have the popup with this message: 

```An error occurred while loading the web debug toolbar (500: Internal Server Error).

Do you want to open the profiler?```

If I push yes the pop disappear and appear again. If I click on cancel i can access the page.

**Comment by seb2411** [comment]
Forgot my last message. After updating the cache everything works with Php 5.5.31.

**Comment by seb2411** [comment]
Going back to Php 5.6.17 the problem is back.

**Comment by seb2411** [comment]
The admin/dev/dev.log
http://pastebin.com/Qr2rjFVb

**Comment by chirimoya** [comment]
Can you provide the phpinfo for php 5.6? (/admin/_profiler/phpinfo)

**Comment by chirimoya** [comment]
Or can you check the value of the 'display_errors' setting?

**Comment by seb2411** [comment]
Here the Phpinfo:
[phpinfo.pdf](https://github.com/sulu-io/sulu/files/85716/phpinfo.pdf)

**Comment by chirimoya** [comment]
on difference I can spot is `display_startup_errors = Off` ... can you try?

**Comment by seb2411** [comment]
Fixed. It was that.

**Comment by webmozart** [comment]
This issue occurred again and we did some investigation what is happening: When submitting the form with "Enter", the event was handled twice by JavaScript: once through the native "submit" event, and once more through the "keydown" event of the input field. The duplicate login request causes "data.url" to be undefined in some cases (which we did not properly figure out), resulting in a redirect to "/admin/undefined" (the value of "data.url" is simply appended to "/admin").

**Comment by manuxi** [comment]
was able to reproduce this on xampp with 1.3.0/1.3.1
display_startup_errors = Off in php.ini fixed this

**Comment by alexander-schranz** [comment]
This error also happens on 5.6 when the response of the POST have a deprecation message e.g.:

`Your PHP Version is 5.6.15, but always_populate_raw_post_data = 0. $HTTP_RAW_POST_DATA is deprecated from PHP 5.6 onwards and will be removed in PHP 7.0. This will stop the installer from running. Please open your php.ini file and set always_populate_raw_post_data to -1. If you need more help please call your hosting provider.`

in this case setting the following in php.ini should fix it:

```ini
always_populate_raw_post_data = -1
```
