### ISSUE TITLE
Changing template and values does not work

### ISSUE THREAD

**Issue by danrot** [sulu-io/sulu#1929]
When changing a template in the content or snippet section, the save afterwards doesn't work as expected. The `DocumentManager` uses the old template to iterate over the values, which results in ignoring properties which only exist in the new template.

**Comment by danrot** [comment]
@dantleech Why are we using the form here: https://github.com/sulu-io/sulu/blob/310e120e9cd1f1390442bcba4e7b0963bae7ee7b/src/Sulu/Component/Content/Mapper/ContentMapper.php#L238

This is the cause of the issue. Our form type already uses the template of the document to iterate over the properties, but the template is not updated before the `persist` call a few lines later.

**Comment by dantleech** [comment]
@danrot it binds the submitted data to the document.

**Comment by danrot** [comment]
@dantleech But based on the wrong template... Wouldn't it be good enough to let the value form only write the `stagedData`, and let a subscriber execute [this line](https://github.com/sulu-io/sulu/blob/310e120e9cd1f1390442bcba4e7b0963bae7ee7b/src/Sulu/Bundle/ContentBundle/Form/Type/AbstractStructureBehaviorType.php#L54)?

Then we could rank this subscriber lower than the one changing the template, seems like the cleanest solution to me. In general I think it's a bit problematic to split this task like this between the form and document manager.

**Comment by dantleech** [comment]
Well, this code would actually be at the controller level. It is only here for BC.

The DocumentManager subscribers currently also have this "responsiblity", yes. But this is very bad, and is coupled to the problem of the current Content Types excepting raw POST data.

It is one of the things we need to fix with the content type refactoring.

The final result should be that the data from the request is bound to the Document class, after which no futher transformation will be required.

**Comment by danrot** [comment]
@dantleech What you are talking about is not the actual problem here. Even if the controller would contain this code, we would still have the same problem. The line I have pointed out in the previous comment would still be executed too early (i.e. the template of the document would still not be changed).

I would say the form is only responsible for staging the content (which works fine), but the document manager should "commit" it, since the document manager is also changing the template, and the commit is not valid before.

This has nothing to do with the content types, since the values which are passed to the content types are already wrong (i.e. just the default values, because the old template is used).

**Comment by dantleech** [comment]
Skype? Google Hangouts?
