### ISSUE TITLE
Sulu Build Prod dont install fixtures

### ISSUE THREAD

**Issue by alexander-schranz** [sulu-io/sulu#1947]
When install sulu with `app/console sulu:build prod`.
The database fixtures are missing.

**Comment by danrot** [comment]
Are you talking about stuff like the countries? This is working for me, which version are you using, and what is the output of the script?

**Comment by alexander-schranz** [comment]
Newest stable version: `1.1.5`

Did the following steps:

```
app/console sulu:build prod
app/console sulu:security:role:create
app/console sulu:security:user:create
// clear cache
```

Then wanted to visit the page and it did say System Collection with ID 2 not found. Did look at the data base all `*_types`  tables where empty.

Didn't have any error in the output. Did run then app/console sulu:build fixtures to get the fixtures and create role/user again. Then it did work.

**Comment by alexander-schranz** [comment]
cant reproduce it on mac will try it again on windows at the evening.

**Comment by alexander-schranz** [comment]
tried again today seems to work.
