### ISSUE TITLE
Longer translation codes than 60 characters

### ISSUE THREAD

**Issue by mob8607** [sulu-io/sulu#1997]
I think it would be nice if translations-codes could be longer than 60 chars, as they can be longer when we use namespaced translation-codes

**Comment by danrot** [comment]
Why can't they be longer? Because of the database schema?

**Comment by mob8607** [comment]
yes, Code.orm.xml in translateBundle:

<field name="code" type="string" column="code" length="60"/>

**Comment by wachterjohannes** [comment]
i will extend the max length to 255.
