### ISSUE TITLE
Problems installing on a Mac using Sqlite

### ISSUE THREAD

**Issue by EdwinLove** [sulu-io/sulu#2010]
Just tried installing on a Mac (Yosemite) using Sqlite. On running build I got the following error
```
      [Doctrine\DBAL\DBALException]
      Operation 'Doctrine\DBAL\Platforms\AbstractPlatform::getListDatabasesSQL' is not supported by platform.
```

Not sure if it is a config error or a problem with sqlite

**Comment by danrot** [comment]
That sounds more like a Doctrine than Sulu issue to me... Have you checked if all parameters have been correctly passed in the container?

**Comment by webmozart** [comment]
Replaced by #2048.
