### ISSUE TITLE
Incorrect hreflang implementation

### ISSUE THREAD

**Issue by c00n84** [sulu-io/sulu#2022]
Google writes following:

Google has detected that some pages on your site have implemented the rel-alternate-hreflang tag incorrectly. In particular, there seems to be a problem with incorrect language and region codes, or incorrect bi-directional linking (if page A links with hreflang to page B, there must be a link back from B to A as well). Google uses the hreflang attributes to serve the correct language or regional URL to the right users in search results.

In my case the problem seems to be the backlinking which is described above.

**Comment by c00n84** [comment]
@wachterjohannes possible problems:

- if a webspace is on "https"
- if a page is available in only one language, remove  the hreflang tag

**Comment by alexander-schranz** [comment]
@wachterjohannes just to keep in mind that the language choicer on the website need all languages and an url there when the site not exist should link to the startpage but the startpage should not be then in the meta or sitemap.
