### ISSUE TITLE
New contact position should be assigned immediately

### ISSUE THREAD

**Issue by chirimoya** [sulu-io/sulu#2025]
If you add a new position for the contact/organization relation the new position should immediately be selected. Currently you have to assign the new position manually after you have added it.

<img width="575" alt="bildschirmfoto 2016-02-22 um 15 22 46" src="https://cloud.githubusercontent.com/assets/627313/13220755/30dc407e-d978-11e5-9d6c-0550b49e1b36.png">

**Comment by webmozart** [comment]
Can you provide more information about what this ticket is about? In general, most tickets and PRs lack a lot of information that would allow an outsider to participate.

**Comment by chirimoya** [comment]
@webmozart updated

**Comment by webmozart** [comment]
:+1:
