### ISSUE TITLE
internal_links - error 500 during render tree node

### ISSUE THREAD

**Issue by ohalluin** [sulu-io/sulu#2039]
The problem apper when you select one internal link on 'internal_links' property:

Exception:
In: vendor/jackalope/jackalope/src/Jackalope/Query/Row.php at line 156
Column 'node.Title' not found
500 Internal Server Error - ItemNotFoundException

I overridden a sulucontent/js/components/internal-links/main.js to diseable fields title and order on js file. But the result is not navigable, so you can select only first tree node.

**Comment by wachterjohannes** [comment]
this issue seems to be related https://github.com/sulu-io/sulu/issues/2026

@ohalluin do you have multiple webspaces?

**Comment by ohalluin** [comment]
yes i have multiple webspaces. But in your issue #2026, your title implies the problem comes whit locale parameters. But i am not sure in same problem on this context.
For example, my 'single_internal_link' on same template works correctly.

**Comment by wachterjohannes** [comment]
are you use the same locales in both webspaces?

**Comment by ohalluin** [comment]
My webspaces have same locale.
If i use internal_links in other webspace with overriden main.js, I don't have any node in response (but it is normal because i was not yet content in other webspace)

**Comment by wachterjohannes** [comment]
could you show me your overwritten file? maybe there is an other bug

**Comment by ohalluin** [comment]
getColumnNavigationUrl = function() {
            var url = '/admin/api/nodes',
                urlParts = [
                    'webspace=' + this.options.webspace,
                    'language=' + this.options.locale,
                    'webspace-node=true',
                ];

            return url + '?' + urlParts.join('&');
        },

To use $this->cgetNodes($request) (just to test because of method deprecated)

**Comment by ohalluin** [comment]
My apologize. I just rebuild my phpcr content and internal_links works. So is probably same issue because last day i change all locales in my webspace.

**Comment by danrot** [comment]
@ohalluin So can we close that issue? :-)
