### ISSUE TITLE
Length of category_key is limited to 45 characters

### ISSUE THREAD

**Issue by thomasduenser** [sulu-io/sulu#2040]
I wanted to create a category with a long key, then following error appears:

```
code: 1
message: "A category-key has to be unique"
```

This error makes no sense to me because there is definitely not the same key in use, even if the string would get truncated.
In the file `Category.orm.xml` the length of **category_key** is limited to 45. Is there a reason?

Thanks in advance.

**Comment by danrot** [comment]
Found the "error", it is located [here](https://github.com/sulu-io/sulu/blob/develop/src/Sulu/Bundle/CategoryBundle/Category/CategoryManager.php#L303). We catch all the `DBALException`s, which is wrong of course. We should catch the `UniqueConstraintViolationException` here.

Can you try to find out what exception is actually thrown here? Would probably also answer your question :wink:

**Comment by thomasduenser** [comment]
```An exception occurred while executing 'INSERT INTO ca_categories (category_key, default_locale, lft, rgt, depth, created, changed, idCategoriesParent, idUsersCreator, idUsersChanger) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params ["test_test_test_test_test_test_test_test_test_test_test_test_test", "de", 0, 0, 0, "2016-02-24 13:45:52", "2016-02-24 13:45:52", null, 1, 1]: SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'category_key' at row 1"```

I'll just shorten my category keys, but maybe it makes sense to increase the length of the category_key.

**Comment by danrot** [comment]
Actually I thought they just truncate the data, without throwing an error. Is the category still saved in the database? Don't you have a more concise name for that? No matter what limit we set here, somebody will probably always exceed it :wink: But yeah, we can also raise the possible length.

**Comment by thomasduenser** [comment]
Nope, the category is not saved in the database - it just throw's the error that the key is not unique. 

Of course, I've already shortened the key names so there's no issue anymore for me. Maybe there's the requirement of longer keys in future projects.

**Comment by wachterjohannes** [comment]
it should also be validated client-side. then it is not important how long it is.

**Comment by wachterjohannes** [comment]
if mysql is configured in the "strict-mode" it throws an error when truncating data. this seems to happen here. i will change the length of the key to 255 (max length) and validate in the frontend. additionally i will catch only the `UniqueConstraintViolationException` at this point.
