### ISSUE TITLE
Improve the presentation of the info text for template properties

### ISSUE THREAD

**Issue by sabinebaer** [sulu-io/sulu#2049]
The info_text of properties is shown as tooltip. It would be nice if fields with info_text are marked, e.g. with a question mark.

E.g.
```xml
<property name="complicated_property" type="text_line">
    <meta>
         <title lang="en">Complicated property</title>
         <info_text lang="en">This is a complicated property which needs a text to explain how to handle it.</info_text>
    </meta>
</property>
```
is shown as
![info_text_presentation](https://cloud.githubusercontent.com/assets/5627878/13347635/5b08a046-dc6f-11e5-9e0b-07625a7378a5.png)

**Comment by berndhep** [comment]
@chirimoya @sabinebaer There is a clear definition for info texts. 
![bildschirmfoto 2016-02-29 um 15 31 09](https://cloud.githubusercontent.com/assets/7425459/13397263/7a6d9504-def9-11e5-8957-6143a69edbcc.png)
