### ISSUE TITLE
Change runtests.sh to a cross platform php script

### ISSUE THREAD

**Issue by alexander-schranz** [sulu-io/sulu#2084]
Currently the runtests.sh can not be run on windows without a bash emulation.

**Comment by danrot** [comment]
@dantleech Any reason not to do so?

**Comment by dantleech** [comment]
what is a cross-platform script?

The only way I can think of doing this is to write the script in PHP.

**Comment by danrot** [comment]
@dantleech That's what it says in the title ;-) Writing this as a php script has several would also have the advantage that everyone from us is more familiar with that.
