### ISSUE TITLE
ServiceNotFoundException sulu_hash.request_hash_checker

### ISSUE THREAD

**Issue by cbastienbaron** [sulu-io/sulu#2144]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | (develop) 4017651
| Browser Version | 

#### Actual Behavior
[Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException]                                                  
  The service "sulu_snippet.controller.snippet" has a dependency on a non-existent service "sulu_hash.request_hash_checker".  
 
On update sulu, i've got this Exception thrown. Any idea ?

**Comment by alexander-schranz** [comment]
I remember that I had some similar problems after an update and it was that the container in my cache. Did then `rm -rf app/cache/` after that it worked for me.

**Comment by cbastienbaron** [comment]
@alexander-schranz yep already done, but still pbl persist :(

**Comment by wachterjohannes** [comment]
Are you sure you have included the "SuluHashBundle" in the AbstractKernel?

**Comment by cbastienbaron** [comment]
ah yes ! ty @wachterjohannes the update sulu is not easiest

**Comment by wachterjohannes** [comment]
you could stick in in the dicussion about that in this issue https://github.com/sulu-io/sulu-standard/issues/633
