### ISSUE TITLE
Add Apikey input in contact / permission admin

### ISSUE THREAD

**Issue by cbastienbaron** [sulu-io/sulu#2170]
| Q 
| --- | ---
| Bug? | no
| New Feature? | yes
| Sulu Version | master
| Browser Version | 

#### Actual Behavior
Hi Guys,
I would like to add a readonly field `apiKey` in /admin/#contacts/contacts/edit:1/permissions

What is the best way to achieve that, i've already override the `permission.form.html.twig` but data of user is loaded in js, so my question is how to a to do that ?

**Comment by danrot** [comment]
I would say the easiest way is to put that into a separate tab as described in [the documentation](http://docs.sulu.io/en/latest/cookbook/using-tab-navigation.html), and create a separate form and javascript component. It is not that easy to extend a given component, so this is probably the easier way to go. You should have a look at the other javascript components, and ask more specific questions as they come up.

However, we should definitely think about how to make it easily possible to extend the already existing form.

**Comment by cbastienbaron** [comment]
@danrot ty for you're response ;)
