### ISSUE TITLE
Webspace Request Analyzer

### ISSUE THREAD

**Issue by chirimoya** [sulu-io/sulu#274]
- Do we still need the `sulu_core.webspace.request_analyzer.enabled` option (https://github.com/sulu-cmf/sulu/blob/develop/src/Sulu/Bundle/CoreBundle/DependencyInjection/Compiler/RequestAnalyzerCompilerPass.php#L34)
- Do we really need both services? Set Alias? (https://github.com/sulu-cmf/sulu/blob/develop/src/Sulu/Bundle/CoreBundle/DependencyInjection/Compiler/RequestAnalyzerCompilerPass.php#L58)
- Personally I don't like the idea of having a Request-Listener enabled for the backend. E.g. all API calls which have nothing to do with "web spaces" are influenced as well.

**Comment by dantleech** [comment]
If we set the request analyzer services to `public=false` (so that they are removed from the DI container when they are not used) would that close this issue? @chirimoya ?

**Comment by danrot** [comment]
I don't think so, because it will still be executed. But I also don't think we can easily get rid of it, since it is required for some tasks in the backend as well. However, I guess it would be enough to only instantiate one of these two services, instead setting an alias.
