### ISSUE TITLE
[GeneratorBundle] (#1) Mkdir Problem in MacOSx permission denied

### ISSUE THREAD

**Issue by sulu-io-user** [sulu-io/sulu#378]
<a href="https://github.com/wachterjohannes"><img height="50" width="50" src="https://avatars.githubusercontent.com/u/1464615?v=2" /></a>
By @wachterjohannes *from* https://github.com/sulu-cmf/SuluGeneratorBundle/issues/1

sulu:generate:bundle create first subfolder

Example: Sulu/Bundle/TestBundle
Folder: vendor/sulu/test-bundle

create vendor/sulu/test-bundle
then it works ...

**Comment by dantleech** [comment]
Do we even want the GeneratorBundle? Does anybody use it? If not, why not? /cc @chirimoya @danrot

**Comment by danrot** [comment]
I am using the generator bundle every time creating a new bundle, that just doesn't happen every day ;-)

**Comment by danrot** [comment]
But I am thinking about something different now, couldn't the GeneratorBundle from Symfony be extended in a more elegant way?
