### ISSUE TITLE
[AdminBundle] dynamic include CSS of bundles

### ISSUE THREAD

**Issue by sulu-io-user** [sulu-io/sulu#417]
<a href="https://github.com/michaelzangerle"><img height="50" width="50" src="https://avatars.githubusercontent.com/u/1465587?v=2" /></a>
By @michaelzangerle *from* https://github.com/sulu-cmf/SuluAdminBundle/issues/29

at the moment the stylesheet files of other bundles are included in the index.html.twig - better would be a dynamic way

**Comment by janmassive** [comment]
I need to add a css file for a custom SuluBundle

**Comment by wachterjohannes** [comment]
for me the solution for that is `require-css` @danrot could you remember which issue we mentioned this plugin? i think we should do it (:

**Comment by wachterjohannes** [comment]
https://github.com/guybedford/require-css

**Comment by danrot** [comment]
Sadly not :confused: I'll check it out

**Comment by danrot** [comment]
@chirimoya What do you think about require-css?

**Comment by chirimoya** [comment]
+1 require-css

**Comment by danrot** [comment]
Finally! Unbelievable :smile:
