### ISSUE TITLE
[ContentBundle] SmartContent add Filter for Template

### ISSUE THREAD

**Issue by sulu-io-user** [sulu-io/sulu#427]
<a href="https://github.com/alexander-schranz"><img height="50" width="50" src="https://avatars.githubusercontent.com/u/1698337?v=2" /></a>
By @alexander-schranz *from* https://github.com/sulu-cmf/SuluContentBundle/issues/181

for example to get all events on startpage.

**Comment by chirimoya** [comment]
Closing in favor of https://github.com/sulu-io/sulu/issues/1456
