### ISSUE TITLE
[MediaBundle] Long image titles need to be shortened

### ISSUE THREAD

**Issue by sulu-io-user** [sulu-io/sulu#449]
<a href="https://github.com/pjeroen"><img height="50" width="50" src="https://avatars.githubusercontent.com/u/513131?v=2" /></a>
By @pjeroen *from* https://github.com/sulu-cmf/SuluMediaBundle/issues/71

![screen shot 2014-09-03 at 16 52 52](https://cloud.githubusercontent.com/assets/513131/4135886/33befee4-337a-11e4-8ddd-7ae007733897.png)

**Comment by alexander-schranz** [comment]
![bildschirmfoto 2015-03-27 um 14 35 22](https://cloud.githubusercontent.com/assets/1698337/6868772/9c394122-d48e-11e4-8b1a-4e41e5e93c39.png)

seems to be fixed
