### ISSUE TITLE
[MediaBundle] Direct Upload File Size

### ISSUE THREAD

**Issue by sulu-io-user** [sulu-io/sulu#450]
<a href="https://github.com/oliverpretz"><img height="50" width="50" src="https://avatars.githubusercontent.com/u/1152516?v=2" /></a>
By @oliverpretz *from* https://github.com/sulu-cmf/SuluMediaBundle/issues/65

when using the direct upload overlay in the CRM-documents the following error occurs:

"Failed to load resource: the server responded with a status of 413 (Request Entity Too Large)"

File: PDF, size 1.8 MB

**Comment by wachterjohannes** [comment]
@alexander-schranz isn´t this not a server configuration? `max_upload_size` or something like this? /cc @danrot

**Comment by alexander-schranz** [comment]
@wachterjohannes yes the error appears then. I thought the file should be still be from type UploadFile when it errored in symfony but it isnt.
