### ISSUE TITLE
[MediaBundle] Transparent Media has coffee Icon

### ISSUE THREAD

**Issue by sulu-io-user** [sulu-io/sulu#453]
<a href="https://github.com/alexander-schranz"><img height="50" width="50" src="https://avatars.githubusercontent.com/u/1698337?v=2" /></a>
By @alexander-schranz *from* https://github.com/sulu-cmf/SuluMediaBundle/issues/56

![bildschirmfoto 2014-08-06 um 15 09 51](https://cloud.githubusercontent.com/assets/1698337/3827185/22cf2692-1d6b-11e4-8da2-7b7746861854.png)

We can give the Img Tag an background-color to avoid this problem.

**Comment by alexander-schranz** [comment]
fixed with #952
