### ISSUE TITLE
[TagBundle] delete gets inactive when cancel delete dialog

### ISSUE THREAD

**Issue by sulu-io-user** [sulu-io/sulu#474]
<a href="https://github.com/turbo-ele"><img height="50" width="50" src="https://avatars.githubusercontent.com/u/5152633?v=2" /></a>
By @turbo-ele *from* https://github.com/sulu-cmf/SuluTagBundle/issues/22

when canceling delete dialog, the delete buttons gets inactive although items selected.

**Comment by danrot** [comment]
Seems to be fixed in the new design.
