### ISSUE TITLE
[TranslateBundle] Export Bundle Packages back to the bundles

### ISSUE THREAD

**Issue by sulu-io-user** [sulu-io/sulu#481]
<a href="https://github.com/marcelmoosbrugger"><img height="50" width="50" src="https://avatars.githubusercontent.com/u/1998663?v=2" /></a>
By @marcelmoosbrugger *from* https://github.com/sulu-cmf/SuluTranslateBundle/issues/51

The import command takes the xlf files from the different bundles and creates a translation-package per bundle in which the codes from the xlf-file get stored. It would be nice to have an export command which generates xlf-files from these "bundle-packages" and stores them in the corresponding bundles.

At the moment it's only possible to export all translation keys into one json (for the front end) or one xlf file per language. To export all translation keys into one xlf file is not really useful for anything

**Comment by danrot** [comment]
@marcelmoosbrugger Isn't that already solved?

**Comment by marcelmoosbrugger** [comment]
@danrot - no this is still open. At least i haven't done it.
