### ISSUE TITLE
Move Structure Constants from Structure Class to Interface

### ISSUE THREAD

**Issue by alexander-schranz** [sulu-io/sulu#558]
e.g. TYPE_PAGE, TYPE_SNIPPET

**Comment by danrot** [comment]
@dantleech Will this be changed in #685 ?

**Comment by dantleech** [comment]
I think so.. we probably won't need them. (i hope)

**Comment by alexander-schranz** [comment]
@danrot I think this issue can be closed?

**Comment by danrot** [comment]
It's still in the Structure class, but in the compat namespace... I think having a separate issue is not necessary, since the class will be removed while further refactoring anyway.
