### ISSUE TITLE
Moving of page with subpages destroys urls

### ISSUE THREAD

**Issue by c00n84** [sulu-io/sulu#616]
the cached url on the subpages are not correctly updated, which leads to 404 Errors

**Comment by chirimoya** [comment]
ping @wachterjohannes @danrot @c00n84

**Comment by wachterjohannes** [comment]
@chirimoya should be tested i will do this on monday!

**Comment by danrot** [comment]
Actually that was the task of @c00n84 ;-)

**Comment by wachterjohannes** [comment]
ah ok (= perfectly!

**Comment by wachterjohannes** [comment]
@c00n84 have you checked this?

**Comment by wachterjohannes** [comment]
@c00n84 this seems to be fixed with the 0.18 release. if yes please close it!

**Comment by chirimoya** [comment]
@c00n84 can you verify?

**Comment by c00n84** [comment]
@chirimoya @wachterjohannes yes it's fixed with the new release
