### ISSUE TITLE
Serialization problem when data is not loaded

### ISSUE THREAD

**Issue by michaelzangerle** [sulu-io/sulu#675]
When an entity is not loaded fully (not all relations) it can cause an error when the entity is serialized. I know that we partially checked wether the relation is null but it is not everywhere. Should we do this everywhere or is there a better solution?

**Comment by danrot** [comment]
Actually you should make sure that everything you want to serialize is already loaded...

**Comment by michaelzangerle** [comment]
I think that we have use cases where we want to load different relations (and not always all relations) of an entity but we have only one api enity ...

**Comment by danrot** [comment]
Do you remember the serialization groups? ;-)

**Comment by michaelzangerle** [comment]
Do you remember the time needed to add these groups everywhere? ;-) It's a lot simpler to just add a condition in the api entity ...

**Comment by danrot** [comment]
You asked for a better solution, not a simpler one :-P Would definitely go this way.
