### ISSUE TITLE
Configureable main domain for sitemap and redirects

### ISSUE THREAD

**Issue by alexander-schranz** [sulu-io/sulu#686]
Currently the sitemap uses the first Domain/Url in the array.
https://github.com/sulu-cmf/sulu/blob/9e42fff40c57b35993fe85ba9e45e6cdc14725cd/src/Sulu/Bundle/WebsiteBundle/Twig/Sitemap/SitemapTwigExtension.php#L90

The array is sorted by key.(?)

If I add a static domain "static.my-domain.at" and have a main domain "www.my-domain.at" the sitemap uses "static.my-domain.at" to generate the urls.

Maybe we should add the following things to webspace.xml:
1. a option to mark which is my main domain and use this for sitemap generation
2. a option to mark a domain type (static)

**Comment by danrot** [comment]
The main domain makes sense, but what do we need this static for? These sites are not managed by sulu at all, so why do they have to be listed in the webspace config?

**Comment by alexander-schranz** [comment]
I had to add the domain to my webspace else the image generation didnt work correctly

**Comment by alexander-schranz** [comment]
I think a twig extension for the images should also be good which automaticly add the static domain

**Comment by alexander-schranz** [comment]
The error which I get when the static domain is not part of the webspace config:
```
FatalErrorException: Error: Call to a member function getWebspace() on a non-object in 
vendor/sulu/sulu/src/Sulu/Bundle/WebsiteBundle/EventListener/SetThemeEventListener.php line 36
```

**Comment by danrot** [comment]
I think you should get rid of the Sulu overhead, and just configure this URL in the webserver correctly. I guess you don't need Sulu for these static pages, that's why I would not add this options. Who wants to have a CMS for a non-manageable page ;-)

**Comment by danrot** [comment]
Actually I would think it is the better solution to make this configureable in the media bundle, so that you can define some URLs to deliver these assets. For these URLs we could deactivate this listener, so that the error is not thrown anymore.

**Comment by alexander-schranz** [comment]
should static domains not be webspace specific?

**Comment by danrot** [comment]
I don't think so, IMHO the asset URL should not be in the webspace config, since it is not necessarily related to the webspace.

**Comment by alexander-schranz** [comment]
do you know if symfony assets have an option automaticly add a static domain for css/js files?

**Comment by danrot** [comment]
If you use the `asset`-twig function (what you should be doing) it is quite easy to do so: http://stackoverflow.com/questions/7358470/twig-asset-with-cdn-using-symfony-2

**Comment by danrot** [comment]
Is that what you wanted to address in #672 ?

**Comment by alexander-schranz** [comment]
looks good we should use that configuration for staticdomains.
so we only need to fix the problem with this EventListener.
Yes this is more about #672.
The main Domain we also need I think for the sitemap.xml or?

**Comment by danrot** [comment]
Ok, so I close #672 , and as I already wrote, I agree with the main domain, I'll adjust the issue name for that. However, if I am not wrong, currently the first URL in the list is the main URL, and all the others redirect to it. But this option should definitely be available.

**Comment by danrot** [comment]
I've created a separate issue for the deactivation of the RequestAnalyzer, which would solve the problem with the `SetThemeListener`.

**Comment by danrot** [comment]
Forgot to link the issue: https://github.com/sulu-cmf/sulu/issues/799
