### ISSUE TITLE
Internal Link loads value from a previous edited page

### ISSUE THREAD

**Issue by alexander-schranz** [sulu-io/sulu#700]
Sometimes when multiple Pages are edit/created. The Internal or Single Internal Link content types use the value from the page before. When the page is refreshed its ok. Seems to be a problem in JS but dont know how I can directly reproduce the bug, it only happens sometimes.

**Comment by wachterjohannes** [comment]
@alexander-schranz i have checked this a few times with the current release and i cannot reproduce it. can you also try to reproduce it? if you can please reopen this issue
