### ISSUE TITLE
SecurityContext should be able to define locale dependency and available permissions

### ISSUE THREAD

**Issue by danrot** [sulu-io/sulu#709]
Currently the SecurityContext is a simple string defined in the Bundle's `Admin`-class. However, the SecurityContext should also be able to tell the Security system if it is dependent on the locale and which of the seven available permissions (view, write, edit, delete, ...) should be available.

**Comment by chirimoya** [comment]
@danrot still an issue?

**Comment by danrot** [comment]
Partly. I have implemented that a security context can tell the system which permission types(view, write, ...)  are available, but not yet if the permission is dependent on the locale. However, I'd say that's the responsibility of the controller anyway, so I close this issue.
