### ISSUE TITLE
Page save with many children takes to many resources

### ISSUE THREAD

**Issue by alexander-schranz** [sulu-io/sulu#742]
Sometimes you will get on max_execution_timeout or memory problem. 
The problem is the RlpStrategy:adaptResourceLocators function.

1. We should change the children url edit to be handle on kernelTerminate 
2. The performance issue come from the adaptResourceLocators. I think its allso double called every node or more by doing the write of the content type again which calls adaptResourceLocators again see the following lines:
http://github.com/sulu-cmf/sulu/blob/d93d2c045149963b11ab70f95fd95a12b02d997c/src/Sulu/Component/Content/Types/Rlp/Strategy/RlpStrategy.php#L228 and   
http://github.com/sulu-cmf/sulu/blob/d93d2c045149963b11ab70f95fd95a12b02d997c/src/Sulu/Component/Content/Types/Rlp/Strategy/RlpStrategy.php#L235

**Comment by chirimoya** [comment]
https://github.com/sulu-cmf/sulu/issues/741

**Comment by danrot** [comment]
I guess this was fixed with #741 ?

**Comment by danrot** [comment]
@alexander-schranz Isn't that fixed now?
