### ISSUE TITLE
[RFC] DeveloperBundle

### ISSUE THREAD

**Issue by dantleech** [sulu-io/sulu#748]
I propose we create  a DeveloperBundle.

This bundle will contain templates and fixtures for a full website.

It would be disabled by default, maybe enabled by unversioned `config.local.yml` or something.

Old idea, but a good one.

**Comment by danrot** [comment]
For me this is the same as with your suggestion about the generation of random data. It should not be part of the standard installation, because except of developers it is of no use.

**Comment by patkar** [comment]
see #1056

**Comment by dantleech** [comment]
This exists: https://github.com/sulu-io/SuluDeveloperBundle
