### ISSUE TITLE
Add clear local image cache command

### ISSUE THREAD

**Issue by alexander-schranz** [sulu-io/sulu#808]

**Comment by wachterjohannes** [comment]
@alexander-schranz i think the only possibility is to delete the folder? correct me if i am wrong i think thats an easy pick ...

**Comment by alexander-schranz** [comment]
you are correct the command only needs to delete the configurated cache folder normally `web/uploads/media` which is in the `sulu_media.format_cache.path` parameter

**Comment by patkar** [comment]
I'm not so happy with the idea atm. On prod environment, when sites are in a http cache and the format cache get's deleted, then the files are missing but the page is still served from the http cache..

**Comment by alexander-schranz** [comment]
but when the file get access again from the browser. the image will be regenerated. this should work without any problems.

**Comment by patkar** [comment]
I don't get it. The file is generated into the `web/uploads/media/{image-config}` dirs. The rendered site contains this path. So when the path is a plain file, how can Sulu detect it is missing when the page is never request from Sulu (because of http cache)?

**Comment by alexander-schranz** [comment]
there is a controller fallback which will generate the thumbnail. when you upload a new image in sulu it will not generate each image into each format. only when it will be requested it will be generated. this have 2 advantages.

1. only the image format which are used will be generated
2. you can add new images formats without an extra generate image formats command

**Comment by patkar** [comment]
Oh :sweat_smile: A transparent controller in front of the path. Sneaky
