### ISSUE TITLE
Scale smaller images to right resolution

### ISSUE THREAD

**Issue by alexander-schranz** [sulu-io/sulu#809]
If the image format is 1200x600 and the image has only 1000x1000 pixel the image should be scaled to 1000x500. Currently it will not scaled and will return 1000x1000 image which will destroy the theme design.

**Comment by wachterjohannes** [comment]
if you only parse width=1000 and leave height empty in the image formats. It scales the image to 1000x500

**Comment by alexander-schranz** [comment]
But the problem is for fixed image formats for example a square. 
200x200 when the image is 150x100 its better to get a 100x100 image instead of 150x100.

**Comment by alexander-schranz** [comment]
and if this behaviour give you headache I can add an option to the scale/resize function which can you turn on/off this behaviour.
