### ISSUE TITLE
Remove all the previous 1.0 upgrade commands

### ISSUE THREAD

**Issue by danrot** [sulu-io/sulu#819]
I think before releasing the first stable release we should remove our upgrade commands, at the moment there are `sulu:upgrade:0.9.0:resource-locator` and `sulu:upgrade:0.15.0:internal-links`. They don't really look nice, and shouldn't be used after installing 1.0 anyway.

@dantleech already suggested that we could try to use doctrine migrations instead, and maybe there will be something similar for PHPCR one day.

/cc @chirimoya @wachterjohannes

**Comment by patkar** [comment]
:+1: for doctrine migrations

A cleanup of the UPGRADE and CHANGELOG files may be good too.

**Comment by dantleech** [comment]
Also we now have https://github.com/dantleech/PhpcrMigrationsBundle for PHPCR migrations.

**Comment by danrot** [comment]
@c00n84 Which of the upgrade commands do you really need? I would look over all of them anyway, just to be sure not to delete one you really need.

**Comment by danrot** [comment]
My suggestion would be:

Command | Handling
--- | ---
 sulu:upgrade:0.9.0:resource-locator | rename to sulu:content:resource-locator:maintain and move from `CoreBundle` to `ContentBundle`
 sulu:upgrade:0.15.0:internal-links | remove
 sulu:upgrade:0.16.0:time | remove 
 sulu:upgrade:0.17.0:collections | remove
 sulu:upgrade:0.17.0:media | remove
 sulu:upgrade:0.18.0:smart-content-operator | remove

Most of the commands are just here to convert some legacy data formats to the current ones. As said I would like to remove them, since they are not needed in a fresh install and pollute the command namespace.

/cc @dantleech @c00n84 @wachterjohannes @chirimoya

**Comment by c00n84** [comment]
@danrot Perhaps we also need the smart-content-operator command sometimes. It can be used to generally change the operator from OR to AND for tags

**Comment by dantleech** [comment]
+1 

@c00n84 re. the smart content, is that indicative of a missing feature in the admin interface? If necessary we could make a dedicated command for it in any case.

**Comment by danrot** [comment]
Is there really a use-case where you want to change that for every single page? Can't imagine, since you lose all the managed information...
