### ISSUE TITLE
Changing language on add page formular throws 404

### ISSUE THREAD

**Issue by danrot** [sulu-io/sulu#823]
If you want to add a new page to Sulu, and you try to change the language in the following form:
![image](https://cloud.githubusercontent.com/assets/405874/6164911/cf38c924-b2a3-11e4-8938-0dd313f027ae.png)
You will be redirected to the URL `http://sulu.lo/admin/#content/contents/sulu_io/de_at/edit:undefined/content`, which will lead to a 404 error.

**Comment by alexander-schranz** [comment]
i remember this error also appear when @thomasduenser and @wachterjohannes  develop the first version of startpage copy function I think to fix this the same check as in this PR is needed.
https://github.com/sulu-cmf/sulu/pull/777/files

**Comment by danrot** [comment]
As far as I see from this code it is not the same error, because the index page always exists. I probably have to add that this error only occurs if the parent page is ghost page in the selected localization.
