### ISSUE TITLE
live preview: property attribute on <img> tag

### ISSUE THREAD

**Issue by RaphaelHofer** [sulu-io/sulu#830]
The live preview for images doesn't work if you add the property attribute to the <img> tag, only if you add it to a container around the <img>.

greetings, R.H.

**Comment by wachterjohannes** [comment]
the preview selector should handle dom elements like img, a, ... in a diffrent way than others!

I think there is a specifiation for rdfa for this ... i will take a look at this!

**Comment by chirimoya** [comment]
ping @wachterjohannes

**Comment by wachterjohannes** [comment]
@chirimoya there are a few exceptions like (a, img, ...) which have to be implemented (=
