### ISSUE TITLE
Default.xml Template should not be required

### ISSUE THREAD

**Issue by alexander-schranz** [sulu-io/sulu#839]
When creating a new page it requires the default.xml.

**Comment by wachterjohannes** [comment]
you have to set the default template in the config if you don´t want to have a `default.xml` https://github.com/sulu-cmf/sulu-standard/blob/develop/app/config/config.yml#L114

set it to your default template and you can delete `default.xml` . is this enough? otherwise reopen this issue!

**Comment by alexander-schranz** [comment]
but when i have multiple webspaces I dont wanted to use the same default.xml

**Comment by wachterjohannes** [comment]
ok you want to set the default foreach webspace individual?

**Comment by alexander-schranz** [comment]
I think that would be the best for multiple webspaces

**Comment by wachterjohannes** [comment]
and would solve your problem?
