### ISSUE TITLE
Server error on store copied editor content

### ISSUE THREAD

**Issue by tomsvogel** [sulu-io/sulu#847]
"Invalid character found in property \"i18n:de-article\". Are you passing a valid string?"

tested in html mode, paste from Word and direct in editor.

PHPCR on mysql.

**Comment by wachterjohannes** [comment]
if you copy from word you should use the copy from word button ... but yes i think we should validate this on serverside .... /cc @danrot what do you think?

**Comment by tomsvogel** [comment]
content was not copied from word, but i tried all 3 methods to insert.
editor mode, html mode and copy from word dialog

**Comment by danrot** [comment]
The copy from word dialog was created for this, so it's confusing that it is not working...
And what do you want to validate on serverside? And IMHO the text editor should be able to to this on its own...

**Comment by dantleech** [comment]
jackalope-doctrine-dbal requires that the data does not contain any characters that are invalid in XML according to: http://en.wikipedia.org/wiki/Valid_characters_in_XML#XML_1.0

I guess we should apply some "sanitization" to remove strange characters from incoming data.

**Comment by wachterjohannes** [comment]
@danrot at least we should clean the strings before we write it into phpcr ... to avoid this error!

**Comment by tomsvogel** [comment]
hotfix please ;)

**Comment by danrot** [comment]
Ok, we can do that, but I can't promise you that will be a hotfix ;-)

**Comment by chirimoya** [comment]
Shouldn't that be fixed in jackalope-doctrine-dbal? /cc @dantleech

**Comment by chirimoya** [comment]
@tomsvogel ... is this still an issue? /cc @dantleech

**Comment by chirimoya** [comment]
@tomsvogel ... please reopen, if there is still an issue.
