### ISSUE TITLE
Nested properties not working in preview

### ISSUE THREAD

**Issue by Quehnie** [sulu-io/sulu#861]
If I use a Property in a Property like:

![bildschirmfoto 2015-02-23 um 16 59 01](https://cloud.githubusercontent.com/assets/8446502/6331061/4a99cc8a-bb7d-11e4-82c7-2d141421b4f0.png)

and i change my title. It doesn't update my preview, looks like property="season" blocks property="title"

**Comment by wachterjohannes** [comment]
we have to update the css selector here it interprets property in property as a block so we have to check if there is a rel/typof argument to be sure that it is a block

**Comment by wachterjohannes** [comment]
this is not version dependent
