### ISSUE TITLE
Add custom plugins to texteditor

### ISSUE THREAD

**Issue by alexander-schranz** [sulu-io/sulu#864]
for developer it would be good when they can add custom plugins to the ckeditor or use another skin

``` xml
<param name="skin" value="customskin, /bundles/..." /><!-- ckeditor use the same syntax -->
<param name="extra_plugins" value="myplugin1,myplugin2" />
<param name="extra_plugin_paths" value="/bundles/mycustombundle/...,/bundles/mycustombundle2/..." />
<param name="style_set" value="[
                {name: 'Blue Title', element: 'h2', styles: {color: 'Blue'}},
                {name: 'Red Title', element: 'h3', styles: {color: 'Red'}},
                {name: 'CSS Style', element: 'span', attributes: {'class': 'my_style'}},
                {name: 'Marker: Yellow', element: 'span', styles: {'background-color': 'Yellow'}}
            ]" />
```

Hint: Styleset can set directly without register over styleSet.add in CKEDITOR

``` js
config.stylesSet = [...]; 
```

**Comment by stefann-sasori** [comment]
What about adding color choice in the editor ?

**Comment by danrot** [comment]
@stefann-sasori What exactly do you mean by that?

**Comment by stefann-sasori** [comment]
I mean, is it able to display a colorpicker so that my client choose the color he wants for some piece of text. Something like this:
![image](https://cloud.githubusercontent.com/assets/11821158/11836708/59dabdea-a3d4-11e5-92d4-e6f031320a0d.png)

**Comment by danrot** [comment]
Ah, ok... Well, it depends a bit. Do you or @alexander-schranz know any good ckeditor plugin doing this? And @alexander-schranz, would that easily be embeddable?

**Comment by alexander-schranz** [comment]
@stefann-sasori  please try the following config: 

```xml
<param name="toolbar" value='[{"name":"semantics","items":["Format"]},{"name":"basicstyles","items":["Superscript","Subscript","Italic","Bold","Underline","Strike"]},{"name":"blockstyles","items":["JustifyLeft","JustifyCenter","JustifyRight","JustifyBlock"]},{"name":"list","items":["NumberedList","BulletedList"]},{"name":"colors","items":["TextColor","BGColor"]}]' />
<param name="extra_plugins" value="justify,format,sourcearea,link,table,pastefromword,autogrow,colorbutton" />
```

**Comment by alexander-schranz** [comment]
if you want a more extended color chooser also add the `colordialog` to extraPlugins this will shown a more colors link the colorbutton table.

**Comment by stefann-sasori** [comment]
Ok thank you @alexander-schranz it works

**Comment by danrot** [comment]
@alexander-schranz I don't think that this is necessary. Our intention is that the text editor should be as slim as possible.

**Comment by stefann-sasori** [comment]
Yes but i'm now using sulu on prod and the client wants this feature. My view is that if it exists some way to extend any features, it should be documented. Clients have sometimes exotic needs.

**Comment by alexander-schranz** [comment]
@danrot maybe we should add an `add_extra_plugins` and `add_toolbar` parameters where he can just add new plugins and dont need to know which one exists?

**Comment by danrot** [comment]
@alexander-schranz Don't really know what you are talking about... But in general there's nothing to say against making these things easier, but it should not be the default. You know that it's not our philosophy to let the user change stuff like this.

**Comment by alexander-schranz** [comment]
@danrot e.g. for this case would be something like:

``` xml
<param name="add_toolbar" value='[{"name":"colors","items":["TextColor","BGColor"]}]' />
<param name="add_extra_plugins" value="colorbutton,colordialog" />
```

**Comment by danrot** [comment]
Ah, now I know what you are talking about. I don't know if this is a good idea... I would keep it as it is. Having two different options for the same things seems a bit confusing.

**Comment by alexander-schranz** [comment]
ok. when I got some free time I will work on a cookbook tutorial for editor customization.
