### ISSUE TITLE
Page cant be deleted when a page was moved with url history

### ISSUE THREAD

**Issue by alexander-schranz** [sulu-io/sulu#868]
1. I create the following structure
 - A
    - B
       - C
    - D

When I move B into D its not possible to delete D reference error with the old url history uuid.
You must delete B before you can delete D.

**Comment by chirimoya** [comment]
ping @wachterjohannes can you verify, please

**Comment by dantleech** [comment]
If we change so that the `history` property references the `content` instead of the new `route`, would that solve this issue? (we would do that anyway with RoutingAuto).

**Comment by wachterjohannes** [comment]
@chirimoya i have found the bug and i will fix it!
