### ISSUE TITLE
CategoryManager:save unique check is wrong

### ISSUE THREAD

**Issue by dantleech** [sulu-io/sulu#871]
The CategoryManager:save meythod catches all DBAL exceptions and then rethrows as "KeyNotUnique" exception with no message and no parent exception.

This is wrong because :

- Validation should happen at the Model level. not in the manager
- ALL DBAL errors are assumed to be unique constraint violations

Also, when Exceptions intrecepted and new exceptions are thrown, you should *always* pass the old exception as the third argument to the new exception.

**Comment by danrot** [comment]
What exactly is wrong? Can you put a bit more information here?

**Comment by dantleech** [comment]
The CategoryManager:save meythod catches all DBAL exceptions and then rethrows as "KeyNotUnique" exception with no message and no parent exception.

This is wrong because :

- Validation should happen at the Model level. not in the manager
- ALL DBAL errors are assumed to be unique constraint violations

Also, when Exceptions intrecepted and new exceptions are thrown, you should *always* pass the old exception as the third argument to the new exception.

**Comment by dantleech** [comment]
@danrot yes I was doing that. Just getting my head around waffle.
