### ISSUE TITLE
Page deletion should be confirmed if page is referenced

### ISSUE THREAD

**Issue by chirimoya** [sulu-io/sulu#877]
`Uncaught PHP Exception PHPCR\ReferentialIntegrityException: "HTTP 409: 922b6b02-fe82-4b87-8b68-0b45c8bd9fb8 cannot be removed because it is still being referenced"`

**Comment by danrot** [comment]
Somehow fixed in #882, but the optimal solution would be to show another overlay with a list of pages, which references the one which should be deleted. The snippets are already doing that:

![image](https://cloud.githubusercontent.com/assets/405874/6398294/ebee7eae-bdea-11e4-8293-5b1f35779d77.png)

**Comment by danrot** [comment]
@berndhep Somehow this overlay has disappeared... Now I've got the question how to handle the deletion of multiple referenced snippets at once...
