### ISSUE TITLE
Preview Bug - wrong language for render_esi stuff

### ISSUE THREAD

**Issue by thomasduenser** [sulu-io/sulu#890]
The Locale for the preview is wrong for content that is included in the template via render_esi. Translations are translated in the wrong (default?) language instead of the active language.

The bug seems to be in:
PreviewRenderer.php, there's something missing like $request->setLocale(...);

**Comment by danrot** [comment]
@wachterjohannes Can you reproduce that? I can remember that I have already fixed that for the website itself, doesn't that apply here as well?

**Comment by wachterjohannes** [comment]
no we have to set the content language to the "dummy" request of the renderer! i have testet it and it should be easy to fix!
