### ISSUE TITLE
Currencies and Prices config/implementation

### ISSUE THREAD

**Issue by christianbader** [sulu-io/sulu#893]
3.3.2015 @notsure @chirimoya @christianbader @danrot 
* [x] tax classes as fixtures stored in SQL database
* [ ] configuration of currencies are done via webspaces, thus we need to adapt the current xml schema and the xmlReader. The following format may be used:
```
<currency default=true>EUR</currency>
```
* [ ] one default currency for all shops
* [ ] prices and currencies are not depending on any language
* [ ] there is no possibility to choose a specific shop from the UI - all prices and currencies are shown in one tab. Optional: separate dropdown for currencies

**Comment by notsure** [comment]
As we can have multiple shops we can also have multiple "default currencies".
So those default currencies should be listed in PIM on the very top of the list. 

like this:

config Shop A:

````
<currencies>
    <currency default="true">EUR</currency>
    <currency>USD</currency>
    <currency>IDR</currency>
</currencies>
````

config Shop  B:

````
<currencies>
    <currency default="true">CHF</currency>
    <currency>USD</currency>
    <currency>IDR</currency>
</currencies>
````


So on a product page in PIM the list should look like this:

EUR
CHF
USD
IDR

**Comment by danrot** [comment]
Just to be sure: You are not implementing this in this repository, right? We said these changes should only be applied if the shop is include, ergo it should be in some shop bundle.
