### ISSUE TITLE
Media assignment doesn't work after save

### ISSUE THREAD

**Issue by danrot** [sulu-io/sulu#894]
The media assignment works only before the save of a page. After a save it is not possible to assign more image to the field. After reloading the form the media assignment works again.

**Comment by wachterjohannes** [comment]
@danrot is this issue with the old media selection? if yes we could close it!

**Comment by danrot** [comment]
Yeah, I've got it on my list of issues to close after we merge this stuff. It cannot be considered solve at the moment IMO.

**Comment by wachterjohannes** [comment]
yeah thats right(=
