### ISSUE TITLE
Webspaces Shop Config Extension

### ISSUE THREAD

**Issue by christianbader** [sulu-io/sulu#895]
4.3.2015 @danrot @notsure @christianbader

* [ ] Create schema for shop config that includes webspace-1.0.xsd
* [ ] Create own FileLoader which extends XmlFileLoader.php
* [ ] Default currencies are specified in config.yml
* [ ] Assign shop to portal: ```<portal type="shop"> ```
* [ ] Refactor WebspaceManager - Inject ShopCollectionBuilder or WebspaceCollectionBuilder then assign to webspaceCollection:
```
$webspaceCollection = $webspaceShopCollectionBuilder->build(); 
```

**Comment by danrot** [comment]
Shouldn't this be part of #893? I think it is about the same issue. And actually we said it is not part of this repository :-)

**Comment by christianbader** [comment]
Moved to https://github.com/massiveart/POOL-ALPIN/issues/1023
