### ISSUE TITLE
Text editor and location content type should follow parameter naming conventions

### ISSUE THREAD

**Issue by danrot** [sulu-io/sulu#896]
Currently the parameters in the text editor content type are camel cased (e.g. `godMode` instead of of `god_mode`, as in all other content types). This should be adjusted for the sake of consistency.

**Comment by dantleech** [comment]
The refactoring would make all of those snake cased.

**Comment by danrot** [comment]
You are right, I just realized that it is also like that in the location content type. Anywhere else as well?

**Comment by alexander-schranz** [comment]
@danrot we deleted the godMode in the ckeditor (#918 / https://github.com/massiveart/husky/pull/457) update instead there are new options for script and iframe embed.

**Comment by danrot** [comment]
@alexander-schranz But you also kept the wrong naming convention described in this PR? Well, maybe it is a better idea to fix that later all together.
