### ISSUE TITLE
Collection - Popup doesn't disappear

### ISSUE THREAD

**Issue by xandrej** [sulu-io/sulu#899]
In mainmenu choose collections. The popup that appears first on the screen doesn't disappear.

**Comment by chirimoya** [comment]
please english, thx

**Comment by danrot** [comment]
Which popup are you talking about? Can you append a screenshot?

**Comment by xandrej** [comment]
Screenshot: 

![screen shot 2015-03-06 at 11 19 00](https://cloud.githubusercontent.com/assets/4947276/6523724/9ea59ea8-c3f2-11e4-9cd7-efcaf4c2f719.png)

**Comment by berndhep** [comment]
Might be solved with new asset management. Please check again after update.

**Comment by turbo-ele** [comment]
when clicking on Media > collection, this popup appears. you then have to click on the backdrop to remove it

**Comment by wachterjohannes** [comment]
@turbo-ele is solved in the new asset management! will be merged hopefully this week!
