### ISSUE TITLE
Category search

### ISSUE THREAD

**Issue by xandrej** [sulu-io/sulu#901]
In mainmenu choose Categories. Search (in upper left corner) does not work.

**Comment by chirimoya** [comment]
please english, thx

**Comment by danrot** [comment]
Are you talking about the search in the upper right corner? The search on the left side (in the navigation) have been removed recently.

**Comment by xandrej** [comment]
Screenshot:

![screen shot 2015-03-06 at 11 42 27](https://cloud.githubusercontent.com/assets/4947276/6524063/e7e2c980-c3f5-11e4-862f-5421b73f2def.png)
