### ISSUE TITLE
Mainmenu footer is missing

### ISSUE THREAD

**Issue by xandrej** [sulu-io/sulu#904]
Main menu footer is missing as shown in this picture:

![main_menu_footer_missing](https://cloud.githubusercontent.com/assets/4947276/6523954/ffffdb26-c3f4-11e4-850a-90c13ba3a5dc.png)

New permissions group was added.

Permission settings:

1. product - all enabled
2. media - all disabled
3. settings - all disabled
4. security - all disabled
5. global - all disabled
6. webspaces - all disabled
7. salesorder - all disabled

**Comment by danrot** [comment]
Somehow related to #645

**Comment by danrot** [comment]
This happens if there is a section, which has no navigation items. It's not a permission issue, there is a javascript error, because the `renderNavigationItems` of the husky navigation component tries to loop over a non-array.
