### ISSUE TITLE
Link SmartContent and InternalLinks entries to edit mask

### ISSUE THREAD

**Issue by danrot** [sulu-io/sulu#912]
It would be nice if the entries in the smart content (and then also for media, internal links, snippets) are deep links, so that a click leads to the corresponding edit form.

![image](https://cloud.githubusercontent.com/assets/405874/6596811/fe8dacbc-c7f7-11e4-9545-1c6838229a2d.png)

/cc @berndhep WDYT?

**Comment by berndhep** [comment]
Yes!
