### ISSUE TITLE
Media Thumbnail controller fallback image (coffee icon) dont work correctly

### ISSUE THREAD

**Issue by alexander-schranz** [sulu-io/sulu#915]
![bildschirmfoto 2015-03-16 um 11 57 27](https://cloud.githubusercontent.com/assets/1698337/6664860/a9dcaa62-cbd3-11e4-886c-df3a4a4c476a.png)

Broken Images appears instead of fallback Icon

**Comment by danrot** [comment]
A bit more information would be useable :P

**Comment by alexander-schranz** [comment]
@danrot screenshot added

**Comment by danrot** [comment]
How did that happen?

**Comment by alexander-schranz** [comment]
@danrot did test this behaviour it only happens on chrome.
It seems when the http status code is 404 which I set when there is no thumbnail image available for this file(coffee icon fallback) the chrome dont render the fallback image. Should we change the HTTP Status code or what should we do?

**Comment by danrot** [comment]
How is that fallback rendered? It's really strange that this only happens on chrome. And if not totally necessary I would not change the http status code...

**Comment by alexander-schranz** [comment]
If the uploaded file is not an image or cant be converted to an image the coffee icon image is returned with the status 404. If you open the image url directly in a new tab the image is loaded.

**Comment by danrot** [comment]
I don't think that returning the coffee icon with a status code of 404 is a good idea... Chromium's behaviour is correct IMHO.

Returning the coffee icon with every 404 response also means that it will be transferred every time. I would just return a 404 without the coffee icon, and change the path on the client side. Then this would work correctly and the image would only be transferred once.

**Comment by alexander-schranz** [comment]
thats a good idea. I found out that the browser through an event when the image can't be loaded (404).
so we can handle the coffee icon fallback in the frontend.

``` js
$('img').bind('error', function() {
```
