### ISSUE TITLE
Media content type overlay new media drop down hidden

### ISSUE THREAD

**Issue by alexander-schranz** [sulu-io/sulu#927]
![collectiondropdownup](https://cloud.githubusercontent.com/assets/1698337/6684859/5c488f74-cc95-11e4-9842-f694770ce513.gif)

**Comment by danrot** [comment]
@alexander-schranz Can't reproduce, please provide more information. Which browser, OS, Sulu version, ... Have you also tried other browsers?

**Comment by alexander-schranz** [comment]
@danrot Chrome Tested on 0.16.1 and actual develop.
To reproduce it you need to create many collection that the collection count is bigger then the window (not overlay) size.

**Comment by alexander-schranz** [comment]
@danrot I think the husky select component direction is on default (auto) we need to change it to bottom.

**Comment by danrot** [comment]
Fixed with complete new style of media assignment.
