### ISSUE TITLE
Error when not choosing any collection in media upload overlay (content type)

### ISSUE THREAD

**Issue by alexander-schranz** [sulu-io/sulu#928]
Its possible to upload an image with not choosing a collection then the following error appear:

```
code: 5005
message: "Collection with the ID 34 was not found"
```

dont know why it used the 34 ID.
I have collection IDs from 0 - 41 (deleted is 34, 36, 37, 38).
So 34 is the first collection which was deleted very strange behaviour. 
All Collection which where deleted where deleted a long time ago not in this session.

**Comment by danrot** [comment]
@alexander-schranz Isn't the default option in this select to create a new collection? Is it possible at all to not choose a collection?
