### ISSUE TITLE
Cant open last edit page children in Navigation

### ISSUE THREAD

**Issue by alexander-schranz** [sulu-io/sulu#929]
![cantopenlasteditpagechildren](https://cloud.githubusercontent.com/assets/1698337/6685165/b6736cd8-cc97-11e4-9da2-c2e01c3794ed.gif)

**Comment by danrot** [comment]
Have you been editing the "Massive Art" page?

**Comment by wachterjohannes** [comment]
@danrot yeah i have tested this yesterday ... we should check in column view if the children are loaded before preventing action of click!

**Comment by danrot** [comment]
@wachterjohannes So this only happens if there is one element already preselected?

**Comment by wachterjohannes** [comment]
yes (=
