### ISSUE TITLE
When I press the "return" key to login the login screen breaks

### ISSUE THREAD

**Issue by c00n84** [sulu-io/sulu#937]
I insert my username and password and press the "return" key, then the login mask moves half-left and I see the password forgotten screen. But I'm successfully logged in. Tested it in Chrome and Firefox.

![bildschirmfoto 2015-03-21 um 11 30 28](https://cloud.githubusercontent.com/assets/841720/6764696/5fcc7238-cfbe-11e4-998d-596477f6b571.png)

**Comment by danrot** [comment]
The provided fix didn't seem to fix this bug.

**Comment by wachterjohannes** [comment]
@danrot seems to be a typo in scss file (= i have provided a fix for that!
