### ISSUE TITLE
Removed assets are still marked as used in media select

### ISSUE THREAD

**Issue by berndhep** [sulu-io/sulu#947]
When an asset is removed in the media select it still appears as "used" in the media overlay.
![bildschirmfoto 2015-03-27 um 08 17 53](https://cloud.githubusercontent.com/assets/7425459/6863897/c9f4d048-d459-11e4-9f74-f79ef5c798f5.png)

**Comment by danrot** [comment]
Might also be wrong for other content types like internal links, snippets, ...
