### ISSUE TITLE
Should not need to rename structure.dist files for Sulu to work after installation

### ISSUE THREAD

**Issue by dantleech** [sulu-io/sulu#953]
It should not be necessary to copy the `.dist` files after installation, they should be copied in the same way that the `phpcr` and `parameters` files are copied after a composer install.

**Comment by danrot** [comment]
But this should only be done for the default template.

**Comment by patkar** [comment]
see #1056

**Comment by danrot** [comment]
As @patkar already mentioned, this can be seen as duplicate of #1056, so I am going to close this one.
