### ISSUE TITLE
Search on website with umlaut has no result

### ISSUE THREAD

**Issue by c00n84** [sulu-io/sulu#967]
I'm searching for "dreiländer" on the website and I'm getting zero results. If I try to search "dreilaender" then the pages appear in the result.

**Comment by wachterjohannes** [comment]
@dantleech isn`t that fixed?

**Comment by dantleech** [comment]
I thought @chirimoya said that this wasn't a problem with the SearchBundle..

**Comment by danrot** [comment]
@chirimoya Have you already elaborated this bug?

**Comment by chirimoya** [comment]
Issue has been fixed by adding a default analyzer for the `MassiveSearch` (https://github.com/massiveart/MassiveSearchBundle/pull/33)
