### ISSUE TITLE
Title with quotation marks appears wrong in Content structure

### ISSUE THREAD

**Issue by thomasduenser** [sulu-io/sulu#969]
If I have a page title with quotation marks ...
![bildschirmfoto 2015-04-02 um 16 45 40](https://cloud.githubusercontent.com/assets/3875917/6966242/d2fe04ae-d957-11e4-90aa-f30c430c92c9.png)

... there's a bug in the content structure tree view:
![bildschirmfoto 2015-04-02 um 16 45 49](https://cloud.githubusercontent.com/assets/3875917/6966255/e78b679a-d957-11e4-9b2d-6f3e8bfb44e5.png)

If I have a page named "Hello" then the title in the content structure tree view would be empty!

**Comment by danrot** [comment]
In which version does this happen? I thought @wachterjohannes already fixed this...

**Comment by thomasduenser** [comment]
Sorry, forgot to add the version to the Issue - 0.16.1

**Comment by danrot** [comment]
@wachterjohannes Just checked, this is really happening again on latest develop also. Maybe that would be a good start to write unit tests in husky? ;-)

**Comment by wachterjohannes** [comment]
@danrot i thought i fixed that ... yeah your right but we have to fix or to remove the old tests from husky until we can start new ones ... to start we could just implement a behat test for that!

**Comment by danrot** [comment]
We have to do that sooner or later anyway... So I would fix all the tests for this fix. It's clearly a husky and not a sulu issue, so I would say the test should be there.

**Comment by wachterjohannes** [comment]
i have found the issue. by the last refactoring of the column navigation the line:
```js
...
title: this.sandbox.util.escapeHtml(data[this.options.titleName])
...
```
got lost ...
