### ISSUE TITLE
Sitemap not valid for Google

### ISSUE THREAD

**Issue by c00n84** [sulu-io/sulu#991]
Sitemap isn't valid for Google if different domains occur in the same xml. In the example below the entry domain.fr/demande. With subdomains it would be valid for Google (e.g. domain.ch/anfrage and fr.domain.ch/demande could be in the same xml file)

Example:

This is the webspace config:
```xml
...
<environment type="prod">
    <urls>
        <url language="de">www.domain.ch</url>
        <url language="fr">www.domain.fr</url>
        <url language="it">www.domain.it</url>
    </urls>
</environment>
...
```

This is from the **www.domain.ch/sitemap.xml**:
```xml
...
<url>
    <loc>http://www.domain.ch/anfrage</loc>
    <lastmod>2015-01-12</lastmod>
</url>
<url>
    <loc>http://www.domain.fr/demande</loc>
    <lastmod>2015-01-12</lastmod>
</url>
...
```

**Comment by wachterjohannes** [comment]
@c00n84 and how should it look like?

**Comment by alexander-schranz** [comment]
@wachterjohannes the sitemap only should contain one main domain.

`www.domain.ch/sitemap.xml` only should have `domain.ch` (subdomains e.g. fr.domain.ch are allowed)

e.g. if we have a multi portal webspace and a portal e.g. use `domain.ch/myportal` the urls of this portal should also be included in `www.domain.ch/sitemap.xml`
